### ISSUE TITLE
Star macro syntax error 

### ISSUE THREAD

**Issue by patdough5** [dbt-labs/dbt-utils#111]
While developing a model in 0.12.1 and 0.12.2 we have run into an issue with the `dbt_utils.star` macro. We are using an Amazon Redshift database. We received the following error:

```
Found 106 models, 80 tests, 0 archives, 0 analyses, 201 macros, 2 operations, 0 seed files

14:38:12 | Concurrency: 1 threads (target='test_db')
14:38:12 | 
14:38:12 | 1 of 1 START table model public.star_example......................... [RUN]
14:38:21 | 1 of 1 ERROR creating table model public.star_example................ [ERROR in 8.92s]
14:38:21 | 
14:38:21 | Finished running 1 table models in 11.72s.

Completed with 1 errors:

Database Error in model star_example (models/dbt-util-issue/star_example.sql)
  syntax error at or near "FROM"
  LINE 16: FROM __dbt__CTE__underlying_data
           ^
  compiled SQL at target/compiled/fulla/dbt-util-issue/star_example.sql
```

In our situation, dbt will throw a syntax error if the macro is the only field stated in the `SELECT` statement. Here is a minimal, reproducible example: 

```sql
# star_example.sql

{{
  config(
    materialized = 'table'
  )
}}

SELECT
  {{ dbt_utils.star(from = ref('underlying_data'), except = ["team"]) }}
FROM {{ ref ('underlying_data') }}

```

```sql
# underlying_data.sql

{{
  config(
    materialized = 'ephemeral'
  )
}}

SELECT
  'patrick' AS name,
  1 AS team

```

Here is the compiled code: 

```sql
# star_example.sql (compiled)


with __dbt__CTE__underlying_data as (


SELECT
  'patrick' AS name,
  1 AS team
)SELECT
  
FROM __dbt__CTE__underlying_data

```

**Comment by drewbanin** [comment]
Thanks for the report @patdough5. The `star` macro uses the `information_schema.columns` table to find all of the columns in a relation. As such, it definitely won't work with an ephemeral model. I've long had an item on my todo list to 1) throw an error message if an `ephemeral` model is passed to `star` and 2) update the docs accordingly.

Let's leave this issue open and use it to track these changes. Thanks!

**Comment by drewbanin** [comment]
(I'd recommend making `underlying_data.sql` a `view` model here if you're intent on using the `star` macro)

**Comment by patdough5** [comment]
You bet! Thanks a bunch!

**Comment by TjrGithub** [comment]
+1

**Comment by mdesmet** [comment]
@drewbanin : Just playing the advocate of the devil here. Why not supporting ephemeral and execute a query against the generated SQL and fetch the columns from the first row? It might not be ideal for performance, but If it's not in the database it can never be leaked to the outside world, so a sorrow less security wise.

**Comment by mdesmet** [comment]
It wouldn't work if there is no data, temporary tables could work. I understand this would impact the interface of the method (not relation based but model based) but it would be nice to provide this and potentially other relations API methods without the need for permanent materialization.

**Comment by drewbanin** [comment]
Hey @mdesmet - sorry for the delay in getting back to you on this one. Sure thing - we can absolutely do something like what you're describing here.

My long-term preference would be to try to create a view from the ephemeral model, then inspect the resulting columns in the view. I think that something like a temporary table is a neat idea, but it could be a pretty significant performance burden for many typical use-cases for ephemeral models!

The other broad approach we could use here would be to try to run a query like:
```
select * from {{ ref('ephemeral_model') }}
where false
limit 0
```

Most sane query optimizers should take that as a hint to just return the set of columns in the query without actually hitting any data. My bet though is that some query constructs (like `union`s or stacked views) might indeed cause the database to really query some data.

dbt today ships with a macro called `get_columns_in_query`:

https://github.com/fishtown-analytics/dbt/blob/7fa6a363b20bc89e38981e80bea1f9033a0552dc/core/dbt/include/global_project/macros/adapters/common.sql#L30-L45

I bet that we could enhance the `star` macro to use the `get_columns_in_query` macro if we really wanted to. This approach will probably be simpler and less error-prone than the view approach shown above. Curious to hear what you think
