### ISSUE TITLE
Star macro "except" parameter must be uppercased in Snowflake

### ISSUE THREAD

**Issue by foundinblank** [dbt-labs/dbt-utils#115]
In Snowflake, field names are uppercase. The star macro has an `except = []` parameter to where field names can be passed. If using Snowflake, the field names must be in uppercase in the `except` parameter or Snowflake will just ignore it and select all fields. 

Not sure this is an actual bug but felt it should be documented in case anyone else runs into this too.

**Comment by drewbanin** [comment]
Thanks @foundinblank! There are a couple of macros at there that don't work exactly how you would expect on Snowflake. I think this is a function of the macros quoting column (and table) names. Maybe a good paradigm is to not quote these identifiers across the board?

Not sure that we should take immediate action here, but happy to leave this thread open for discussion

**Comment by foundinblank** [comment]
Do you mean, write the field name without quotation marks?

**Comment by drewbanin** [comment]
Correct. We use the [identifier](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/cross_db_utils/identifer.sql#L2) macro in the [star macro](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql#L26), which adds quotes to the column names.

**Comment by tayloramurphy** [comment]
I just ran into this as well. I think we just tend to lowercase everything when comparing field names.

**Comment by emirlej** [comment]
Hi, I encountered the same problem today. It only works if I upper case the column name, even if I skip quoting. 

Isn't the problem this check here in the `star`-code: 

```python
 {%- if col.column not in except -%}
            {% set _ = include_cols.append(col.column) %}

        {%- endif %}
````

Maybe if you change to: `if col.column.lower() not in except.lower()`?

**Comment by drewbanin** [comment]
@emirlej I like that idea - I think there's limited merit to having two columns with the same name but different capitalization in the same table, so we can go ahead and do a case-insensitive comparison here. Is this something you'd be interesting in PRing a fix for?
