### ISSUE TITLE
get_column_from_statement or get_column_from_sql macro

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-utils#122]
Sometimes people want to use statements to return results as a list (in particular when they can't use the `get_column_values` macro)

And then when they do, they have to handle all this weirdness around getting the values from the table object that gets returned, and handling the error that gets thrown on compilation. It either looks something like:
```sql
 {%- call statement('payment_methods', fetch_result=True) -%}

   select distinct
   lower(payment_method)
   from app_data.payments
   order by 1

  {%- endcall -%}

  {%- if execute -%}
  
  {%- set payment_methods = load_result('payment_methods').table.columns['payment_method'].values() -%}
	
  {%- else -%}
  
  {%- set payment_methods = [] -%}
      
  {%- endif -%}
```
or
```sql
    {%- call statement('payment_methods', fetch_result=True) -%}

     select distinct
     lower(payment_method)
     from app_data.payments
     order by 1

    {%- endcall -%}

    {%- set payment_method_results = load_result('payment_methods') -%}

    {%- if payment_method_results and payment_method_results['data'] -%}
        {%- set payment_methods = value_list['data'] | map(attribute=0) | list %}
    {%- else -%}
         {%- set payment_methods = [] -%}
    {%- endif -%}
```

And that's dumb.

I'd like a macro that simplifies this, so that a user can just:
```sql
   {%- call statement('payment_methods', fetch_result=True) -%}

   select distinct
   lower(payment_method)
   from app_data.payments
   order by 1

  {%- endcall -%}

  {% set payment_methods = get_column_from_statement('payment_methods', 'payment_method') %}
```
Or maybe even one step further, and make it `get_column_from_sql`?
```sql
{% set payment_methods_sql %}
   select distinct
   lower(payment_method)
   from app_data.payments
   order by 1
{% endset %}

{% set payment_methods = get_column_from_sql('payment_methods_sql', 'payment_method') %}
```

**Comment by drewbanin** [comment]
@clrcrl love this! Yeah - statements are unwieldy for really no good reason. Long term, I'd like to make it easier to run sql and get results back directly into dbt. This is a great idea in the meantime, and I think it will help us inform how we should implement this in dbt eventually.

I like the `get_column_from_sql` example, but I think we can also make a more general `fetch` macro that takes SQL and returns an agate table. Then `get_column_from_sql` (and other macros like it) can be implemented by just grabbing a column from the table!

I think it would also be cool to make these macros accept default values that should be returned in parsing. I feel less strongly about that (is this really a good idea?) but it's something that popped into my head!

You buy any of this?

**Comment by clrcrl** [comment]
Could also do this with an optional argument for the column position (defaults to the first column) instead of the column name. I imagine 90% of the time the query is going to return one column anyway.

**Comment by clrcrl** [comment]
Ok so using `fetch`, you'd do something like:
```
{% set payment_methods_sql %}
   select distinct
   lower(payment_method)
   from app_data.payments
   order by 1
{% endset %}

{% set results = fetch('payment_methods_sql') %}

{% set payment_methods = get_column(results, 'payment_method') %}
```

**Comment by drewbanin** [comment]
Yeah! I think that's one way this could work. Alternatively, `get_column` can call `fetch` behind the scenes. I think with the example you have here, `get_column` would just be implemented as
```
{{ return(results[column]) }}
```

**Comment by clrcrl** [comment]
Oh that's nice! I like that a lot!
