### ISSUE TITLE
record deduplication

### ISSUE THREAD

**Issue by jthandy** [dbt-labs/dbt-utils#13]
it's very common to need to deduplicate records that are nearly, but not completely, duplicated in source data. once you've done this several times it isn't hard, but it's not obvious how to do this when you first start modeling data. the method is as follows:

- define your key. this may be a single id field or it may be a composite key of many fields.
- choose, for each non-key field, how to pick the resultant value. the most common choices are most recent not null value, the sum, or the max.
- write the window function with the appropriate window clause for each of the above. frequently this involves creating a variable and then repeating it on every line.

**Comment by elyse-weiss** [comment]
DONE! https://github.com/fishtown-analytics/dbt-utils/pull/29
