### ISSUE TITLE
Get_Column_Values Ordering causes Data Irregularities

### ISSUE THREAD

**Issue by tpugliese** [dbt-labs/dbt-utils#195]
Hello,

In using the dbt_utils.pivot() macro, I ran up against dbt_utils.get_column_values()'s code causing unexpected sorting of my Monthly Pivot.  

My pivot code:
`SELECT
  fastly_customer_id,
  {{ dbt_utils.pivot(
      'close_my',
      dbt_utils.get_column_values(ref('revenue_view_test'), 'close_my_numeric'),
      then_value='revenue',
      prefix='Y',
      suffix='M'
  ) }}
FROM {{ ref('revenue_view_test') }}
GROUP BY fastly_customer_id`

Where close_my_numeric is a number between 201401 (January 2014) and 202003 (March 2020). I would expect that my Pivot takes this sorting and sourcing of values into account.  However, when I try to source my Column Values on 'revenue_view_test'.'close_my_numeric', the Order By clause on the 
[dbt_utils.get_column_values()'s Query](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/get_column_values.sql#L44) causes the Monthly Pivot values to be based off of the Order By values, rather than the expected Date Values from the Get_Column_Values, as I would expect.

An ideal outcome would be an alteration of this feature to be able to define how the Macro is ordered, or an ability to use the default ordering of the values.

**Comment by jordan8037310** [comment]
+1 for this issue, the macro should support a `sort` flag where `count` or `alphabetized` were possible.

**Comment by jordan8037310** [comment]
@tpugliese Noting that you can apply `| sort` to your `get_column_values` command in order to get this list alphabetically.

```
dbt_utils.get_column_values(ref('table') ,'field') | sort
```

This can be passed inline with your pivot or you can load it in the header with some variable declarations.
