### ISSUE TITLE
outlier detection

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-utils#2]

**Comment by clausherther** [comment]
What did you have in mind here? I have use a custom test that checks whether values are within ±n standard deviations from some prior n-day rolling average that could apply here.

**Comment by jayziic** [comment]
Interested to also know more about what this feature in testing is! 🙏

**Comment by joellabes** [comment]
> Interested to also know more about what this feature in testing is! 🙏

The `testing` label is for work related to dbt's data tests, not stuff that's _in testing_ and near release, sadly 😞 

You could check out the dbt_expectations package though, maybe https://github.com/calogica/dbt-expectations#expect_column_values_to_be_within_n_moving_stdevs would be useful?

**Comment by jayziic** [comment]
> > Interested to also know more about what this feature in testing is! 🙏
> 
> The `testing` label is for work related to dbt's data tests, not stuff that's _in testing_ and near release, sadly 😞
> 
> You could check out the dbt_expectations package though, maybe https://github.com/calogica/dbt-expectations#expect_column_values_to_be_within_n_moving_stdevs would be useful?

😞 all good, thanks for the reply!
