### ISSUE TITLE
Union Relation Macros Fails for Tables With Array Fields in BigQuery

### ISSUE THREAD

**Issue by sokser** [dbt-labs/dbt-utils#202]
In BigQuery, if you have repeated fields (e.g ARRAY), the `union_relations` macro fails as it tries to cast the array as a type.

https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/union.sql

**Comment by clrcrl** [comment]
Hi @sokser, can you add a snippet of some offending code? 

(I should definitely add this as an issue template...)

It's really helpful for us if you add the following info to a bug report:
## Steps to reproduce
## Expected results
## Actual results
