### ISSUE TITLE
Enable quoting column names for `unpivot` macro

### ISSUE THREAD

**Issue by ghost** [dbt-labs/dbt-utils#216]
I have a table whose column names are quoted, like "BX 759 - long column name".

When I try to unpivot this table, the column names fetched don't contain quotes and the macro doesn't put the quotes in them, thus the macro fails.

**Comment by dbeatty10** [comment]
Since this is to `unpivot` as https://github.com/dbt-labs/dbt-utils/pull/135 was for `pivot`, I'm updating from a bug to a feature request.
