### ISSUE TITLE
standardize test macro parameters 'where', 'condition', 'from_condition', 'to_condition', ...

### ISSUE THREAD

**Issue by marianneke** [dbt-labs/dbt-utils#255]
### Describe the feature
Standardize names of kwargs for conditions to select rows in test macros, and use either explicit argument or kwargs.

### Additional context
Currently, there are several test macros that allow the user to implement tests only for a subset of rows, which is really helpful. Only when writing my own macros that do that, I found it difficult to pin down the right naming convention, since macros follow different conventions, including:
- The macro `test_expression_is_true` has `condition` as an explicit macro variable
- The `test_*_where` macros define these conditions as kwargs, but the naming is not universal: most have `where`, but `test_relationships_where` has `from_condition` and `to_condition`.

It would be helpful if there were a general consensus around whether kwargs or explicit variables are the way to define these conditions, and how to name them in a way that makes it obviously generalizable to tests involving multiple models

### Who will this benefit?
Users of test macros can more easily guess which optional parameters may be present if the names are standardized.

### Are you interested in contributing this feature?
Yes, though I would definitely need input since it involves naming conventions

**Comment by joellabes** [comment]
@marianneke this'd be great! It could probably even be backwards compatible by switching all other arguments to be `where` (for the sake of this conversation, but I agree picking _a_ standardised name would benefit from wider input) and then deprecating the old argument names in a similar way to the [unpivot macro](https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/unpivot.sql)
