### ISSUE TITLE
Question: what do these lines in `test_equality` test for?

### ISSUE THREAD

**Issue by marianneke** [dbt-labs/dbt-utils#256]
https://github.com/fishtown-analytics/dbt-utils/blob/b736cf6acdbf80d2de69b511a51c8d7fe214ee79/macros/schema_tests/equality.sql#L63-L66

In the equality schema test macro, the total number of distinct elements appearing in one table, and not the other is counted, bu counting the number of rows in `union`, which makes sense. However, the test also adds the above lines, counting the absolute difference between number of elements in either of the sets: `a_minus_b` or `b_minus_a`. I'm not sure what case this is testing for: if either of these have any rows in them, the number of rows in `union` would not be zero and the test would fail.

**Comment by MartinNowak** [comment]
![image](https://user-images.githubusercontent.com/288976/106586001-3f5c5b00-6548-11eb-917a-09131adb558c.png)

After determining that the intersection is empty
https://github.com/fishtown-analytics/dbt-utils/blob/b736cf6acdbf80d2de69b511a51c8d7fe214ee79/macros/schema_tests/equality.sql#L54-L56
this just seems to check that the count of rows is the same
https://github.com/fishtown-analytics/dbt-utils/blob/b736cf6acdbf80d2de69b511a51c8d7fe214ee79/macros/schema_tests/equality.sql#L64-L65.

I guess this tries to deal with duplicates that might get dropped as part of the `EXCEPT DISTINCT`.
https://github.com/fishtown-analytics/dbt-utils/blob/b736cf6acdbf80d2de69b511a51c8d7fe214ee79/macros/cross_db_utils/except.sql#L14
