### ISSUE TITLE
Adding "column sort" option to pivot. 

### ISSUE THREAD

**Issue by calebreed** [dbt-labs/dbt-utils#261]
Would it be possible to add a "sort" option into the pivot? 

One helpful use case of this function is showing date values in ascending or descending order for reporting purposes, which is not currently an option in the existing macro.

```
pivot(column,
               values,
               alias=True,
               agg='sum',
               cmp='=',
               prefix='',
               suffix='',
               then_value=1,
               else_value=0,
               quote_identifiers=True,
               distinct=False,
               reverse=False) %}

{% for v in values|sort(reverse=reverse) %}
```

https://github.com/fishtown-analytics/dbt-utils/blob/b736cf6acdbf80d2de69b511a51c8d7fe214ee79/macros/sql/pivot.sql#L54

**Comment by jordan8037310** [comment]
@calebreed - assuming that you're using `dbt_utils.get_column_values`, the sort should likely happen there before being fed into the pivot. See #195 related.

**Comment by jordan8037310** [comment]
@calebreed - Cross positing a solution for #195: 

Noting that you can apply `| sort` to your `get_column_values` command in order to get this list alphabetically.

```
dbt_utils.get_column_values(ref('table') ,'field') | sort
```

This can be passed inline with your pivot or you can load it in the header with some variable declarations for your pivot function.
