### ISSUE TITLE
Using union_relations macro with include paramater doesn't select any columns and results in error

### ISSUE THREAD

**Issue by KellyBurdine** [dbt-labs/dbt-utils#266]
### Describe the bug

I was successfully using the macro union_relations with the optional exclude parameter. However when I switched to using include I received the error 'SQL compilation error:
  syntax error line 19 at position 12 unexpected 'from'.' 
When I opened the compiled file I noticed that the compiled SQL wasn't selecting any of the columns I listed in the include paramater. It was only selecting the source model followed by a comma and the from statement thus triggering the SQL error. It appears the macro is not working as intended. 

### Steps to reproduce

Create a model using the union_relations macro and use the optional "include" parameter. List columns in the include parameter. I also renamed my source column, but I'm not sure if that is related to the bug.

### Expected results

I would expect all columns listed in the include parameter array to be in each select statement and not end in a comma before the from causing a syntax error. 

### Actual results

The macro is not calling any columns, but the source model column. I've confirmed these columns do exist in my underlying ref models and can query them from those tables in Snowflake.

### Screenshots and log output

Here is a screenshot of my model script:
<img width="789" alt="Screen Shot 2020-08-13 at 3 27 21 PM" src="https://user-images.githubusercontent.com/8404391/90184054-25507580-dd7a-11ea-9831-de3f78aa0568.png">

Here is a screenshot of part of the compiled script 
<img width="552" alt="Screen Shot 2020-08-13 at 3 22 38 PM" src="https://user-images.githubusercontent.com/8404391/90183581-5bd9c080-dd79-11ea-874e-ebd770ba64e5.png">

Here is a screenshot of the error: 
<img width="763" alt="Screen Shot 2020-08-13 at 3 32 37 PM" src="https://user-images.githubusercontent.com/8404391/90184136-42854400-dd7a-11ea-9e20-8cf1365e722b.png">

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.17.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```

**The operating system you're using:**
MacOS Mojave Version 10.14.6

**The output of `python --version`:**
Python 3.7.7

**Contents of packages:: **
  - package: fishtown-analytics/dbt_utils
    version: 0.5.1

### Are you interested in contributing the fix?

No, going on extended leave in a few weeks

**Comment by grahamwetzler** [comment]
I also ran into this issue but I realized the problem was that I was using lowercase column names. Snowflake objects are uppercase by default.

**Comment by grahamwetzler** [comment]
A good solution to this could be to raise an error if no columns are selected.

**Comment by dbeatty10** [comment]
Fixed by https://github.com/dbt-labs/dbt-utils/pull/473
