### ISSUE TITLE
dbt_utils.pivot function fails on empty table

### ISSUE THREAD

**Issue by aadityahippo** [dbt-labs/dbt-utils#280]
### Describe the bug
dbt_utils.pivot function does expect at least one record to be populated in the source table. If there is no record in source table, this function fails with a nonetype object error as it does not found values to loop through.

### Steps To Reproduce
Use dbt_utils.pivot function/macro for an empty table and do the run.

### Expected behavior
Function should silently pass with no records generated. It should not fail. 

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ *] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.18.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0

```

**The operating system you're using:**
Mac

**The output of `python --version`:**
Python 3.7.3

**Comment by sungchun12** [comment]
I can take this on!

**Comment by sungchun12** [comment]
@aadityahippo I imagine you get an error like in the screenshot below.
![image](https://user-images.githubusercontent.com/19176976/130280757-0ddbe8a8-5241-4909-8d71-cd6739d992b3.png)

What's the use case for silently passing without error? Would it be more helpful to raise an error message? See example below.

```bash
Compilation Error in model dim_suppliers_empty_pivot (models/marts/core/dim_suppliers_empty_pivot.sql)
  Cannot pivot an empty table/view. Ensure the upstream dependency has populated rows.
  
  > in macro pivot (macros/sql/pivot.sql)
  > called by macro default__pivot (macros/sql/pivot.sql)
  > called by model dim_suppliers_empty_pivot (models/marts/core/dim_suppliers_empty_pivot.sql)
```

**Comment by tivoo** [comment]
Any update on this? Running in to the same issue with my models and would just want the function to create an empty table instead of give a compilation error. Thanks in advance.

**Comment by karthik-viswanathan-alludo** [comment]
Hi all, did we find a fix for this. I am encountering this issue and would appreciate any help to fix it. Thanks.

**Comment by SPTKL** [comment]
Is there a solve for this?

**Comment by cecabrera** [comment]
Having the same issue

**Comment by eedduuar** [comment]
any workaround for this ? 
Thanks
