### ISSUE TITLE
Some dbt_utils macros do not work with Spark SQL

### ISSUE THREAD

**Issue by bdelamotte** [dbt-labs/dbt-utils#291]
### Describe the bug

It appears that many dbt_utils macros are not supported with Spark SQL due to how a lot of the macros are casting with `::` instead of `cast`

### Steps to reproduce

1. Add dbt_utils to your packages.yml file:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
```

2. Create a simple model with the following SQL:
```
select {{ dbt_utils.current_timestamp() }}
```

### Expected results

A model should be created just fine.

### Actual results

```
Runtime Error in model dbt_test (models/staging/dbt_test.sql)
  Database Error
    Error running query: org.apache.spark.sql.catalyst.parser.ParseException: 
    mismatched input ':' expecting <EOF>(line 6, pos 21)
    
    == SQL ==
    /* {"app": "dbt", "dbt_version": "0.18.1", "profile_name": "databricks", "target_name": "dev", "node_id": "model.dbt_databricks.dbt_test"} */
    create or replace view brian_dev_stg.dbt_test
      
      as
        select 
        current_timestamp::
    ---------------------^^^
        timestamp
    

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

```

### Screenshots and log output

![Screen Shot 2020-11-04 at 5 38 50 PM](https://user-images.githubusercontent.com/8355841/98183091-9f4d5200-1ec4-11eb-80f3-7248961b581c.png)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: Spark SQL)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
  - spark: 0.18.0
```

**The operating system you're using:**
macOS Catalina Version 10.15.7
**The output of `python --version`:**
Python 3.7.6

### Additional context

Here is one place where casting is done by `::` instead of cast()
https://github.com/fishtown-analytics/dbt-utils/blob/9feaccc327a7409298a2bc362db53c2e597024fa/macros/cross_db_utils/current_timestamp.sql#L6

### Are you interested in contributing the fix?

Yes! I am happy to change all the `::` to cast() or provide another solution. I would love to contribute to dbt-utils!

**Comment by emilieschario** [comment]
@jtcohen6 I know that dbt utils is outside of core, but do you have any thoughts here on where the core-supported plugins start and end vs things like this? I was under the impression the dbt core --> has plugins and if that was the case, dbt utils would support those core plugins. But maybe that's not true?

Or maybe Spark is just behind so this is the first time this has been caught?

**Comment by clrcrl** [comment]
I'm not a spark expert, but I do know that there's a separate [spark-utils](https://github.com/fishtown-analytics/spark-utils) package that is likely useful here!

**Comment by jtcohen6** [comment]
IMO "plugin packages" are definitely the answer here, and `spark-utils` is the proof point.

Thanks to adapter-based macro dispatching, introduced in v0.18.0, you can install a package that "shims" support for _another_ package's macros. So far, I've created `spark__` implementations of [a subset of dbt-utils macros](https://github.com/fishtown-analytics/spark-utils/tree/master/macros/dbt_utils/cross_db_utils) that don't natively work on Spark.

As long as you install both packages, and define a var in `dbt_project.yml` like:
```yml
vars:
  dbt_utils_dispatch_list: ['spark_utils']
```

Throughout your project, you can call macros such as `dbt_utils.dateadd`, and dbt will _actually_ use `spark_utils.spark__dateadd` behind the scenes.

**Comment by jtcohen6** [comment]
And it works even more "out of the box" in v1.2: https://github.com/dbt-labs/dbt-spark/pull/359

Closing this one, which has been open for a while :)
