### ISSUE TITLE
test_unique_where macro may violate Redshift operator order of precedence

### ISSUE THREAD

**Issue by danatbench** [dbt-labs/dbt-utils#294]
### Describe the bug
When using the unique test to concatenate two fields as documented at [testing an expression](https://docs.getdbt.com/reference/resource-properties/tests/#testing-an-expression), Redshift may report the error:
```
ERROR:  operator does not exist: text || boolean
HINT:  No operator matches the given name and argument type(s). You may need to add explicit type casts.
```

### Steps to reproduce
Consider the case of 2 integer columns that are concatenated as documented for the purposes of testing uniqueness. Modifying the example in the tests documentation,

```
version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: "order_id || '-' || item_id"
```

test_unique_where will produce a query that might look something like this:

```
SELECT 1 || '-' || 2
WHERE 1 || '-' || 2 IS NOT NULL
GROUP BY 1 || '-' || 2
HAVING count(*) > 1;
```

Executing this query on Redshift will deliver: `ERROR:  operator does not exist: text || boolean`

### Expected results

Users are able to use unique test on multiple columns as documented

### Actual results

Users may receive error `ERROR:  operator does not exist: text || boolean` or something like it

### Screenshots and log output
N/A

### System information
N/A

**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:**
macOS Mojave 10.14.6

**The output of `python --version`:**
`Python 2.7.16`

Alternatively, output of `python3 --version`: `Python 3.7.4`

### Additional context
The issue appears to be with the order of operations on this line: https://github.com/fishtown-analytics/dbt-utils/blob/9feaccc327a7409298a2bc362db53c2e597024fa/macros/schema_tests/test_unique_where.sql#L13

Perhaps the {{ column_name }} reference should be encapsulated in parentheses?

### Are you interested in contributing the fix?
Sure, but I would need help. It seems trivial for someone who's already a contributor.

**Comment by jtcohen6** [comment]
@danatbench Does this work if you instead define the test as
```yml
version: 2

models:
  - name: orders
    tests:
      - unique:
          column_name: "(order_id || '-' || item_id)"
```
?

**Comment by danatbench** [comment]
@jtcohen6, yes it does. That is the syntax we're using in our testing to accommodate.
