### ISSUE TITLE
Use `md5_binary()` instead of `md5()` for `hash` function on Snowflake

### ISSUE THREAD

**Issue by ghost** [dbt-labs/dbt-utils#303]
### Describe the bug
Reportedly, Snowflake cannot properly micro-partition the UUID string generated by `md5`, and performs significantly better doing joins with `md5_binary`.

### Steps to reproduce
Join a few large tables on surrogate keys in Snowflake.

### Expected results
Performs something akin to a join on an integer id, or at the very least as well as a join across multiple columns (for instance an id and timestamp).

### Actual results
Performs worse than joining on multiple columns, which give Snowflake information on partitioning.

### System information
**Which database are you using dbt with?**
- [x] snowflake

**Comment by clrcrl** [comment]
Hey hey @grantwinship — do you know if this would be a breaking change? i.e. does `md5(my_col)` product a different result to `md5_binary(my_col)`? I'm assuming it does

**Comment by grantwinship** [comment]
yea - anybody who updated would have to full refresh all their tables that use surrogate keys

**Comment by clrcrl** [comment]
dangggg okay that's going to be quite the breaking change, not sure exactly the best way to roll it out :(

**Comment by grantwinship** [comment]
yep yep - i have some ideas around that -- i want to test it on a big data set first and make sure it's enough of an improvement to warrant it at all first though. open to any suggestions on that front if something good comes to mind.

**Comment by clausherther** [comment]
Why not make this optional via an argument? That way new implementation could use the binary key and older models wouldn't break. The old string version could be deprecated at some point by switching the default to binary.

**Comment by grantwinship** [comment]
> yep yep - i have some ideas around that
(that was the main idea) 😄 @clausherther -- we're on the same page 👍🏻

**Comment by jayziic** [comment]
I think *part* of the snowflake performance issue is that the surrogate_key() function generates a random hashed value. Intentionally so. 

IIUC, especially for these large tables, using a randomised key for joining is not the way to go as any natural data ordering that exists is lost making Snowflake highly unaware of where to find the rows while performing the join.  This results in what is known as "shuffling". 

Thus i think its worth thinking about the purpose of this macro. 
* If its to be hashed and randomize for privacy purposes, it currently fulfills this. 
* If its to be a *short-enough UUID for joining* across objects, it's probably not the most performant for the above shuffling reason, at least in snowflake.


It may be better, in the second case, to instead consider a method to implement a UUID calculation which retains any natural ordering that would benefit snowflake's computation. What this is I am not sure, I can only think of concatenation but that is not "short-enough" IMO. But I do believe a `md5_binary()` is still randomised and the shuffling issue will likely still downgrade performance.
