### ISSUE TITLE
get_column_values should return default if not executing

### ISSUE THREAD

**Issue by jmriego** [dbt-labs/dbt-utils#304]
### Describe the bug
I think get_column_values should return default if not executing.
The issue I'm describing is that this function has a `default` parameter that will be returned if no data is found. But if DBT is not on execution mode, it will return an empty string
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17

### Steps to reproduce
The easiest way I can think of showing the issue is having a model using this function and surrogate_key. We actually use surrogate_key to calculate a row hash, not really a surrogate key, but the example should work anyway
```
{% set rep_types = dbt_utils.get_column_values(source_table, 'rep_type', default=[]) %}
...
{{ dbt_utils.surrogate_key(columns) }} AS row_hash
```

### Expected results
I would expect it to return `[]` as that's defined as the default value in my code

### Actual results
It's returning an empty string instead `''`

### Screenshots and log output
```
Running with dbt=0.18.1

Warning: the `surrogate_key` macro now takes a single list argument instead of multiple string arguments. Support for multiple string arguments will be deprecated in a future release of dbt-utils. The slice.advertiser_rep_assignment_current model triggered this warning.
```

### System information
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.0", "<0.7.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - redshift: 0.18.1
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - postgres: 0.18.1
```

### Additional context
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17

### Are you interested in contributing the fix?
I can't do this now but I'm getting my company to agree on the CLA

**Comment by joellabes** [comment]
Closing this as resolved by #386 (and again in #533 😅 )
