### ISSUE TITLE
insert_by_period materialisation breaks when combined with certain Redshift string functions

### ISSUE THREAD

**Issue by oscarknagg** [dbt-labs/dbt-utils#328]
### Describe the bug

When using the `insert_by_period` materialisation in combination with some Redshift string functions the first non-empty insert fails with `error:  Value too long for character type`

I know that the following string functions are affected (see next section to reproduce):
- [TRIM](https://docs.aws.amazon.com/redshift/latest/dg/r_TRIM.html)
- [REPLACE](https://docs.aws.amazon.com/redshift/latest/dg/r_REPLACE.html)

There may be more but I haven't done a full investigation.

### Steps to reproduce

Create some dummy data in your Redshift cluster
```
create table raw_dummy_data AS (
    select
        '2021-01-02'::date as date_column,
	'def' as some_string
)
```

Define the following model as `test_table.sql`
```
{{
    config(
        materialized='insert_by_period',
        period='day',
        timestamp_field='date_column',
        start_date='2021-01-01',
        stop_date='2021-01-03'
    )
}}


with one_day_data as (

    select
        *
    from raw_dummy_data
    where
        __PERIOD_FILTER__
)

, string_logic as (
    select
        date_column
--        , trim(some_string) as trimmed
        , replace(some_string, 'c', '') as replaced
    from one_day_data
)

select *
from string_logic
```

Then attempt to run this table. This should reproduce the error if either `trimmed` or `replaced` columns are included.
```
dbt run -m test_table --full-refresh
```

### Expected results

The insert for the first period succeeds

### Actual results

The insert for the first period fails with `Value too long for character type`

### Screenshots and log output
The log output when failing:
```
Running with dbt=0.18.1
Found 73 models, 243 tests, 2 snapshots, 0 analyses, 353 macros, 0 operations, 0 seed files, 113 sources

16:37:27 | Concurrency: 4 threads (target='prod')
16:37:27 |
16:37:27 | 1 of 1 START insert_by_period model public.test_table................ [RUN]
16:37:29 + Running for day 1 of 2
16:37:30 | 1 of 1 ERROR creating insert_by_period model public.test_table....... [ERROR in 2.34s]
16:37:30 |
16:37:30 | Finished running 1 insert_by_period model in 5.68s.

Completed with 1 error and 0 warnings:

Database Error in model test_table (test_table.sql)
  Value too long for character type
  DETAIL:
    -----------------------------------------------
    error:  Value too long for character type
    code:      8001
    context:   Value too long for type character varying(1)
    query:     28949298
    location:  string.cpp:175
    process:   query0_92_28949298 [pid=7271]
    -----------------------------------------------
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
```

**Which database are you using dbt with?**
- [ ] postgres
- [ x ] redshift
- [ ] bigquery
- [ ] snowflake

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

### Additional context

I know what the issue is. When the insert_by_period table is created its done with a `create table as` with the `__PERIOD__FILTER__` set to `false`. See https://github.com/fishtown-analytics/dbt-utils/blob/bbba960726667abc66b42624f0d36bbb62c37593/macros/materializations/insert_by_period_materialization.sql#L105
This results in the `trimmed`/`replaced` columns being of type `character varying(1)`.
I think this is because Redshift is determining the column types from the result set of empty data,
which is [expected](https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-varchar-or-character-varying) for varchar types.

Secondly, the `adapter.expand_target_column_types` in the materialisations fails to expand this column to the size
of the inserted data. I don't know why this is.

Also, a roughly equivalent model with the `incremental` materialisation works fine but `insert_by_period` is better for my use case.

## Workaround

Doing an explicit `CAST` in the model SQL solves this i.e. replace `trim(some_string)` with 
`CAST(trim(some_string)) as varchar(100)` stops the error on the first insert.

### Are you interested in contributing the fix?

I'd be very interested in contributing a fix. I'm working on it locally, could do with a hand making sure this doesn't break other peoples use cases.

**Comment by felipefrancisco** [comment]
Just ran into the same issue, +1
