### ISSUE TITLE
expresson_is_true schema test is wrong when the expression evaluates to null

### ISSUE THREAD

**Issue by haleemur** [dbt-labs/dbt-utils#342]
### Describe the bug
the expression_is_true test generates a SQL statement like below. This is actually testing for `expression is true or null`.

```
with validation_errors as (
select 
    * 
from schema_name.table_name
where not(<expression>)
)

select count(*)
from validation_errors
```

### Steps to reproduce

setup (on postgresql 13):
```
create table test_expression_is_true (a, b) as (
  values (1, 2),
         (2, 3),
         (3, null)
  )
```
generated query for expression_is_true where expression: `b > a`
```
with validation_errors as (
select 
    * 
from test_expression_is_true
where not(b > a)
)

select count(*)
from validation_errors
```

### Expected results
the test should fail with 1 row

### Actual results
the test passes
### System information

```
packages:
  - git: "https://github.com/fishtown-analytics/dbt-utils.git"
    revision: 0.1.21
```

**Which database are you using dbt with?**
- [ x ] other (specify: athena)

**The output of `dbt --version`:**
```
0.16.1
```

### Are you interested in contributing the fix?
yes, i think the fix is relatively simple. 

instead of `not (expression )` the where clause should be `not(expression) or (expression) is null` to test for `expression_is_true`

**Comment by JoshuaHuntley** [comment]
Correct me if I'm wrong, but setting condition = FALSE results in a pass every time, right? The current code looks like this:

```
with meet_condition as (
    select * from {{ model }} where {{ condition }}
),
validation_errors as (
    select
        *
    from meet_condition
    where not({{expression}})
)
select count(*)
from validation_errors
```

Setting condition = FALSE results in a zero row meet_condition CTE:

```
with meet_condition as (
    select * from {{ model }} where FALSE
),
```

Shouldn't the logic look more like this?

```
with meet_condition as (
    select * from {{ model }} 
),
validation_errors as (
    select
        *
    from meet_condition
    where {% if condition %}not {% endif %}( {{expression}} )
)
select count(*)
from validation_errors
```
