### ISSUE TITLE
Broken links to schema tests including not_null_where

### ISSUE THREAD

**Issue by jtalmi** [dbt-labs/dbt-utils#347]
When you click the "source" link next to these tests, it brings you to a 404:

https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/schema_tests/not_null_where.sql

should point to

https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/schema_tests/test_not_null_where.sql

**Comment by joellabes** [comment]
Looks like this is fixed now!
