### ISSUE TITLE
get_column_values() returning datetime.date(YYYY, MM, DD) instead of date value

### ISSUE THREAD

**Issue by ghost** [dbt-labs/dbt-utils#355]
When using the function `get_column_values()` on a date column I'm getting the string datetime.date(YYYY, MM, DD) instead of the actual date.

I'm using it as it follows:
```
{% macro get_column_values_from_query() -%}
{% set date_list= dbt_utils.get_column_values(table=ref('dates'), column='date_column', default=[]) %}
{{ log(date_list, info = True) }}
{%- endmacro %}
```

Which returns me `date_list = [datetime.date(1970, 1, 1)]` instead of `date_list = ['1970-01-01']`. When I try it with a common string it works fine but similar thing happens to numbers (Decimal('1234')).

ref('dates') will return only dates in the format YYYY-MM-DD. I tried casting it as string but still got the same thing.

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - git: "https://github.com/fishtown-analytics/dbt-utils.git" # git URL
    revision: 0.6.4 # tag or branch name
```

**The output of `dbt --version`:**
```
installed version: 0.19.0
```

**Comment by MDamon** [comment]
Any resolution to this?

**Comment by joellabes** [comment]
Hi @MDamon, I just tried this out. I could reproduce the issue when working with it as a python object in Jinja, but when using it as a variable in templating they came out as dates. 

Example: 

```
{% set dates = dbt_utils.get_column_values(ref('dbt_metrics_default_calendar'), 'date_year') %}

{% for d in dates | sort %}
  select dateadd('day', 10, '{{ d }}') {% if not loop.last %}union all {% endif %}
{% endfor %}
```

Renders to 
```

  select dateadd('day', 10, '2010-01-01') union all 

  select dateadd('day', 10, '2011-01-01') union all 

  select dateadd('day', 10, '2012-01-01') union all 

  select dateadd('day', 10, '2013-01-01') union all 

  select dateadd('day', 10, '2014-01-01') union all 
[...]
```

![image](https://user-images.githubusercontent.com/7335046/154181112-6fbf6ee3-7546-42f7-bcb2-9551ffe4e0d1.png)

Can you say more about your use case?

**Comment by asysuev** [comment]
I can add, that in my use case I'm trying to use a list of dates in NOT IN comparison, because <> for a big list of dates is compiling not so well
