### ISSUE TITLE
get_column_values macro causes the compiler to run infinitely if the table references is materialized as ephemeral

### ISSUE THREAD

**Issue by heysweet** [dbt-labs/dbt-utils#358]
### Describe the bug
From the user, using the Cloud IDE:
```
I think that the problem is actually with dbt_utils package and get_column_values
macro. I tried to compile models that have that macro and they don't error, but
they just leave the compiler to run forever
After further investigation, I think that the macro causes compiler to run infinitely
if the table referenced is materialized as ephemeral

...
I found a way. to make it work now that I changed the referenced
table to be materialized as view
```

### Steps to reproduce
I actually don't have enough context to fully know repro steps, but presumably start by trying to use the get_column_values macro on a table materialized as ephemeral.

### Expected results
A table materialized as ephemeral should likely produce the same results as a table that is materialized as a view, or we should error out immediately to let users know this configuration is not valid.

### Actual results
User saw an infinite spinner.

### Are you interested in contributing the fix?
I could try, but I'm just on support rotation and trying to file this bug to people who have more context.

**Comment by heysweet** [comment]
After talking to @jtcohen6 it appears that dbt_utils.get_column_values is not meant to work with ephemeral models. Similar macros throw errors, and this one doesn't appear to currently! The likely fix is to throw an error when trying to use dbt_utils.get_column_values is not meant to work with ephemeral models with ephemeral models.

**Comment by jtcohen6** [comment]
I don't know exactly why the infinite spinner happened (some weird product of `statement` + RPC + IDE?), but the short answer here is that `dbt_utils.get_column_values` should use the [`_is_ephemeral`](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/cross_db_utils/_is_ephemeral.sql) check to raise an exception if the `table` argument is an ephemeral model. Similar to other macros that do this today:

https://github.com/fishtown-analytics/dbt-utils/blob/489a44bb7ebad1a6d9ba762fdcd7dc6a9fea7e0d/macros/schema_tests/equality.sql#L23
https://github.com/fishtown-analytics/dbt-utils/blob/489a44bb7ebad1a6d9ba762fdcd7dc6a9fea7e0d/macros/sql/star.sql#L7

**Comment by dbeatty10** [comment]
I believe this is resolved by https://github.com/dbt-labs/dbt-utils/pull/518 🤞 

Please let me know if that is not the case and I will re-open this.
