### ISSUE TITLE
Need to add accepted_range to the schema test table of contents list

### ISSUE THREAD

**Issue by keelyl** [dbt-labs/dbt-utils#379]
### Describe the bug
The quicklink to the accepted_range schema test is missing from the table of contents.

### Steps to reproduce
Look at the table of contents in the README

### Expected results
That test should be present in the TOC for easier navigation

### Actual results
It isn't there.

### Screenshots and log output
not valid

### System information
not valid

### Additional context
Not valid

### Are you interested in contributing the fix?
I would love to

**Comment by joellabes** [comment]
Resolved by #435
