### ISSUE TITLE
dbt_utils.get_column_values fails when using SQL Server adapter

### ISSUE THREAD

**Issue by jhoolachan** [dbt-labs/dbt-utils#387]
Hello,

Running _dbt_utils.get_column_values_ fails with "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Each GROUP BY expression must contain at least one column that is not an outer reference" when working with the SQL Server adapter. The issue is caused by the "group by 1" clause in the following portion of the _get_column_values_ code:

```
select
    {{ column }} as value

from {{ target_relation }}
group by 1
order by {{ order_by }}
```

To recreate this issue, run the following script on an Azure SQL or SQL Server instance:

  ```
create table #temp (
      id int
  )
  insert #temp (id)
  values (1), (2), (3)
  
  select id as value
  from #temp
  group by 1
```

The issue can be resolved by replacing "group by 1" with "group by {{ column }}":

```
select
    {{ column }} as value

from {{ target_relation }}
group by {{ column }}
order by {{ order_by }}
```

Thank you!

**Comment by swanderz** [comment]
@jhoolachan can you move this issue to the https://github.com/dbt-msft/tsql-utils? That's the packages that will make _most_ dbt-utils macros work with SQL Server.
