### ISSUE TITLE
Using dateadd() macro to filter on date partitioned column results in full table scan

### ISSUE THREAD

**Issue by winzee** [dbt-labs/dbt-utils#393]
### Describe the bug
In BigQuery, using the dateadd cross database utility to filter on a date partitioned column results in a full table scan instead of an optimized partition scan.

### Database used
- [x] bigquery

### Steps to reproduce
The following dbt model 

```
SELECT *
FROM huge_date_partitioned_table
WHERE date >= {{ dbt_utils.dateadd(datepart = 'day', interval = -7, from_date_or_timestamp="CURRENT_DATE()") }} 
```

Will be transformed into the following final SQL
```
SELECT *
FROM huge_date_partitioned_table
WHERE date >= 
         datetime_add(
             cast( CURRENT_DATE() as datetime),
         interval -7 day
         )

```

Test this on a big date partitioned table you have to see the resulting scan size.

### Expected results
In my case, a 16 GB scan

### Actual results
In my case, a full table scan (hundreds of GB)

### See the difference by changing the query to this on your big date partitioned table:

```
SELECT *
FROM huge_date_partitioned_table
WHERE date >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
-- or "WHERE date >= CURRENT_DATE() - 7" which also works now in BigQuery also results in an optimized scan.

```

### Additional context

The casting of the date to a datetime is what throws off the BigQuery optimization. If this macro is strictly to be
used for date, the casting should be removed or the final result should be cast back into a DATE. This code actually results in an optimized table scan:

```
SELECT *
FROM huge_date_partitioned_table
WHERE date >= CAST({{ dbt_utils.dateadd(datepart = 'day', interval = -5, from_date_or_timestamp="CURRENT_DATE()") }} AS DATE)
```

### Are you interested in contributing the fix?
Unfortunately I don't have the time or the resources to contribute to this fix at the present time.

**Comment by jtcohen6** [comment]
@winzee By any chance, do you know _why_ filtering on `datetime` types prevents BigQuery from pruning partitions? I was running into this issue over in https://github.com/dbt-labs/dbt/pull/3386#issuecomment-863415719 as well. It doesn't make a lot of sense to me, given that it's possible to [partition on `datetime`-type columns](https://cloud.google.com/bigquery/docs/partitioned-tables#date_timestamp_partitioned_tables), and to limit the number f partitions scanned when querying by [including that column in a `where` statement](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#querying_partitioned_tables_2).

Without better information, I'm inclined to think this is a BigQuery bug

**Comment by winzee** [comment]
@jtcohen6, in the partitioned table with which I have the problem, the partitioning field is of type DATE and partitioned by DAY. I initially thought that is why BigQuery was doing a full scan unless I cast the expression to DATE().

Now, given this example below taken from [dbt-bigquery/issues/717](https://github.com/dbt-labs/dbt-bigquery/issues/717), which are performed on a table partitioned by day on a datetime column, my conclusion does not make sense anymore.

```
-- `events` is partitioned by day on the datetime column `created_at`
select * from events where datetime_trunc(created_at, DAY) in (current_date) -- 650GB
select * from events where timestamp_trunc(created_at, DAY) in (current_date) -- 100MB
select * from events where date(created_at) in (current_date) -- 100MB
```

Hence, I am also inclined to think it might be a Bigquery bug: it's not logical that it would prune for timestamps and dates, but not datetimes.
