### ISSUE TITLE
Recency does not work as expected for datepart day

### ISSUE THREAD

**Issue by alepuccetti** [dbt-labs/dbt-utils#414]
### Describe the bug

Given a current date of `'2021-09-10'` running this test with `datepart: day` and `interval: 3` it should succeed if I have data in my table with a `datestamp >= '2021-09-07'`.
However, this test fail because the `threshold` is defined as type `datetime`.

To fix this, I could configure the interval to be `4` and the threshold will be a day before. The test will work anyway but it is be semantically wrong and easy to miss interpret.

### Steps to reproduce
Configure the test as follow, `datestamp` is a column of type `date`.
```yml
      - dbt_utils.recency:
          datepart: day
          field: datestamp
          interval: 3
```

### Expected results
Assuming that the current date `'2021-09-10'` this tests should succeed if I have data with `datestamp >= '2021-09-07'`. 

### Actual results
The test fail because because it use as threshold a type `datetime` and compared with the type `date` of the table it returns a failure.

### Screenshots and log output
The generated test SQL:
```sql
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      



with recency as (

    select max(datestamp) as most_recent
    from `project_id`.`dataset_id`.`table_id`

)

select

    most_recent,
    

        datetime_add(
            cast( 
    current_timestamp
 as datetime),
        interval -3 day
        )

 as threshold

from recency
where most_recent < 

        datetime_add(
            cast( 
    current_timestamp
 as datetime),
        interval -3 day
        )




      
    ) dbt_internal_test
```

If I run just the code for `dbt_internal_test` the result I get is the following:
```
most_recent | threshold
2021-09-07 | 2021-09-07T06:40:19.603626
```

This is because `most_recent` is type `date` and `threshold` is type `datetime`. If I cast the `threshold` to `date`, the test succeed as expected:
```sql
date(
        datetime_add(
            cast( 
    current_timestamp
 as datetime),
        interval -3 day
        )
)
```

The generated SQL should cast/truncate the `threshold` to the same "type" or "level" of the column we are comparing too.

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```bash
installed version: 0.20.2
   latest version: 0.20.2

Up to date!

Plugins:
  - bigquery: 0.20.2
```

**Comment by joellabes** [comment]
Resolved by #731
