### ISSUE TITLE
Deprecation Warning from macros/schema_tests/not_null_proportion.sql

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-utils#415]
### Describe the bug
`dbt run` on a project that has `dbt-utils` installed will trigger a Deprecation Warning.  

### Steps to reproduce
Set up a simple dbt project with dbt-utils installed.  

### Expected results
`dbt run` gives no warnings.

### Actual results
`dbt run` produces a Deprecation Warning.

### Screenshots and log output
```
(env) emily@Emily-Rockman jaffle-shop % dbt run
Running with dbt=0.21.0-b1
* Deprecation Warning: The "packages" argument of adapter.dispatch() has been
deprecated. Use the "macro_namespace" argument instead.
Raised during dispatch for: test_not_null_proportion
For more information, see:
https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch
Found 2 models, 4 tests, 0 snapshots, 0 analyses, 353 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

13:22:41 | Concurrency: 4 threads (target='dev')
13:22:41 |
13:22:41 | 1 of 2 START table model dbt_testing.my_first_dbt_model.............. [RUN]
13:22:41 | 1 of 2 OK created table model dbt_testing.my_first_dbt_model......... [SELECT 2 in 0.09s]
13:22:41 | 2 of 2 START view model dbt_testing.my_second_dbt_model.............. [RUN]
13:22:42 | 2 of 2 OK created view model dbt_testing.my_second_dbt_model......... [CREATE VIEW in 0.06s]
13:22:42 |
13:22:42 | Finished running 1 table model, 1 view model in 0.29s.

Completed successfully

Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.2
```
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0-b1
```

### Additional context
This is related to the recent changes in [Cherry Pick: not null proportion schema test #411](https://github.com/dbt-labs/dbt-utils/pull/411).  `macro_namespace` should be used instead of `packages` in `macros/schema_tests/not_null_proportion.sql`.   See [docs](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#for-package-maintainers) for more info.

**Comment by jtcohen6** [comment]
Good call @emmyoop, thanks for opening!

@jasnonaz Apologies for not catching the outdated `dispatch` usage in #375/#411. This should be as simple as replacing this line:

https://github.com/dbt-labs/dbt-utils/blob/c7be76a2715d897755390e2a9a29d70026ae73c3/macros/schema_tests/not_null_proportion.sql#L2

With:

```sql
{{ return(adapter.dispatch('test_not_null_proportion', 'dbt_utils')(model, **kwargs)) }} 
```
