### ISSUE TITLE
In 0.7.2, dbt_utils.star does not select all of the columns that it should select

### ISSUE THREAD

**Issue by EPNickBosma** [dbt-labs/dbt-utils#417]
### Describe the bug

We have found that with dbt_utils 0.7.2, `star` does not select all the columns that it should. Some of our models in production fail to build because `star` is not pulling out an ID column that it should be pulling out.

This does not happen with `star` on dbt_utils 0.7.1, so we've put our main branch back on that version for the time being.

### Steps to reproduce

Unsure on _exact_ repro steps, except to say that once `dbt-labs/dbt_utils 0.7.2` is installed, `dbt_utils.star` is liable to leave columns out of its selection even though they're not in the `except` list. In our case it's an "id" column that's not being selected, so the fact that its name is `id` may or may not be technically relevant.

In our case, we're using `star` to pull things out of a source as opposed to a model - again, this may or may not be technically relevant.

### Expected results

When using `dbt_utils.star`, we expect to see all of the columns in the source that we're referring to pulled out, except any columns we've used the `except` list to exclude.

### Actual results

There is a column excluded that we did not specify as a column that should be excluded - in a sense, `dbt_utils.star` simply misses the column.

### Screenshots and log output

We have model code as follows -- note that we do use an `except` list but we do not specify that 'id' should be excluded:

```
with countries as (
    select {{dbt_utils.star(source('organisations', 'countries'), except=['currencyid','phoneprefix','outboundemail', 'inboundemail'])}}
    from {{source('organisations', 'countries')}}
)

select 
    id as country_id,
    ....
from countries
```

The compiled SQL as per dbt_utils 0.7.2 begins as follows - note that there is no `id` column:

```
with countries as (
    select "name",
  "abbreviation",
  "countrycode2char",
  "smallflagurl",
  "defaultdatasetgroupid",
  "defaulttimezoneid"
    from "reporting"."schools"."countries"
)

select 
    id as country_id,
....
```

The compiled SQL as per dbt_utils 0.7.1 begins as follows - note that there **is** an `id` column as there should be:

```
with countries as (
    select "id",
  "name",
  "abbreviation",
  "countrycode2char",
  "smallflagurl",
  "defaultdatasetgroupid",
  "defaulttimezoneid"
    from "reporting"."schools"."countries"
)

select 
    id as country_id,
    ....
```

A screenshot of the columns in the relevant source table:

![image](https://user-images.githubusercontent.com/62360475/133543122-23b33624-4cb8-476d-987b-49b71718372f.png)

### System information (dbt_utils 0.7.2 is installed without being explicitly listed because it's depended upon)
packages:
  - package: dbt-labs/codegen
    version: 0.4.0

  - package: dbt-labs/redshift
    version: 0.5.0

  - package: fivetran/fivetran_log
    version: [">=0.4.0", "<0.5.0"]
  
  - package: dbt-labs/audit_helper
    version: 0.4.0

  `#` - package: fivetran/hubspot
  `#`   version: [">=0.4.0", "<0.5.0"]

  - package: calogica/dbt_expectations
    version: [">=0.4.0", "<0.5.0"]

  - git: https://github.com/fivetran/dbt_hubspot.git
    revision: feature/calculated_fields
    warn-unpinned: false

**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
Using 0.20.2 on cloud

### Additional context
I think the above covers it

### Are you interested in contributing the fix?
I don't think I'm the best person to write code around this.

**Comment by jasnonaz** [comment]
Hi there - good catch and thanks for the detailed writeup. Can you run locally with the changes in https://github.com/dbt-labs/dbt-utils/pull/418/files and let me know if that fixes the issue?
