### ISSUE TITLE
Equality test: failures => '0' is not of type integer

### ISSUE THREAD

**Issue by TimoKruth** [dbt-labs/dbt-utils#443]
### Describe the bug
When I run an equality test on a seed and a model/table I get the error that '0' is not an integer. 
It works in version 0.20.2 but not anymore in 0.21.0

### Steps to reproduce
Create following  3 files in corresponding folders for seeds and models.
testcsv.csv
```
"A" 
1
```
test.sql
`select 1 as A from dual`
test.yml
```
version: 2
seeds:
  - name: testcsv
    columns:
    - name: A
    tests:
      - dbt_utils.equality:
          compare_model: ref('test')
          compare_columns:
            - A
```
`dbt seed`
`dbt run`
`dbt test` (--schema optionally)
### Expected results
```
Running with dbt=0.20.2
Found 64 models, 15 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 25 seed files, 77 sources, 0 exposures

13:36:02 | Concurrency: 2 threads (target='unittest')
13:36:02 |
13:36:02 | 1 of 1 START test dbt_utils_equality_testcsv_A__ref_test_............ [RUN]
13:36:03 | 1 of 1 PASS dbt_utils_equality_testcsv_A__ref_test_.................. [PASS in 0.17s]
13:36:03 |
13:36:03 | Finished running 1 test in 0.57s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### Actual results
```
Running with dbt=0.21.0
Found 64 models, 15 tests, 0 snapshots, 0 analyses, 376 macros, 0 operations, 25 seed files, 77 sources, 0 exposures

13:31:58 | Concurrency: 2 threads (target='unittest')
13:31:58 |
13:31:58 | 1 of 1 START test dbt_utils_equality_testcsv_A__ref_test_............ [RUN]
Unhandled error while executing test.dib.dbt_utils_equality_testcsv_A__ref_test_.145311c1ec
'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['failures']:
    {'type': 'integer'}

On instance['failures']:
    '0'
13:31:58 | 1 of 1 ERROR dbt_utils_equality_testcsv_A__ref_test_................. [ERROR in 0.15s]
13:31:58 |
13:31:58 | Finished running 1 test in 0.49s.

Completed with 1 error and 0 warnings:

'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['failures']:
    {'type': 'integer'}

On instance['failures']:
    '0'

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Screenshots and log output
```
Unhandled error while executing test.dib.dbt_utils_equality_expected__calc_gueltig_von_TF1_META_GUELTIG_VON__ref_calc_gueltig_von_.3c591b58f9
'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['failures']:
    {'type': 'integer'}

On instance['failures']:
    '0'
```
### System information
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4
```

**Which database are you using dbt with?**
- [-] postgres
- [-] redshift
- [-] bigquery
- [-] snowflake
- [x] other (specify: Exasol)

**The output of `dbt --version`:**
```
 dbt --version
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
```

### Additional context
Same dbt-exasol adapter is used in both versions.

### Are you interested in contributing the fix?
I would need a hand. Can't figure out where it goes wrong or why. 
I guess it failes at this place in dbt-core but since it depends on this dbt-utils.equality test I posted it here:
https://github.com/dbt-labs/dbt-core/blob/719b2026ab847ab887d3638c81a351b0f6f96158/core/dbt/task/test.py#L212

Let me know if I can help any further

**Comment by joellabes** [comment]
Hi @TimoKruth, thanks for opening - I _suspect_ that this is actually a Core issue (or potentially even an issue with the exasol adapter itself), but before I send you off somewhere else let's do a bit more debugging! 

Can you post the SQL for the compiled query here as well please? It will probably be located at a path like`target/compiled/your_project_name/path/to/model/something.yml/schema_test/dbt_utils_equality_*.sql`

My best guess is that the result is being output as a string instead of an integer which is why you're having problems. Not sure what changed in dbt core between 0.20.2 and 0.21 that would cause that though.

**Comment by TimoKruth** [comment]
cat target/compiled/dib/unittests/test.yml/schema_test/dbt_utils_equality_testcsv_A__ref_test_.sql :
```
-- setup
with a as (
    select * from UT_DOCKER.testcsv
),
b as (
    select * from UT_DOCKER.test
),
a_minus_b as (
    select A from a
    except
    select A from b
),
b_minus_a as (
    select A from b
    except
    select A from a
),
unioned as (
    select 'a_minus_b' as which_diff, a_minus_b.* from a_minus_b
    union all
    select 'b_minus_a' as which_diff, b_minus_a.* from b_minus_a
)
select * from unioned
```
And from RUN folder
 cat target/run/dib/unittests/test.yml/schema_test/dbt_utils_equality_testcsv_A__ref_test_.sql :
```
select

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 as failures,

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 != 0 as should_warn,

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 != 0 as should_error
    from (

-- setup

with a as (
    select * from UT_DOCKER.testcsv
),
b as (
    select * from UT_DOCKER.test
),
a_minus_b as (
    select A from a
    except
    select A from b
),
b_minus_a as (
    select A from b
    except
    select A from a
),
unioned as (
    select 'a_minus_b' as which_diff, a_minus_b.* from a_minus_b
    union all
    select 'b_minus_a' as which_diff, b_minus_a.* from b_minus_a
)
select * from unioned
    )
```

I removed some empty lines for length reasons.

**Comment by TimoKruth** [comment]
@joellabes I actually tested the scripts on the exasol and they do **not** output a string. So I can only see it to be converted somewhere inside the code of dbt.

**Comment by joellabes** [comment]
In that case, I think you'd be best to open an issue on the exasol adapter, as it won't be something that dbt-utils itself can fix. Does that sound right to you?

**Comment by TimoKruth** [comment]
Possible hacky solutions see at [dbt-core](https://github.com/dbt-labs/dbt-core/issues/4335)
Further work will be discussed at [dbt-exasol](https://github.com/tglunde/dbt-exasol/)
