### ISSUE TITLE
unpivot on aws athena: SYNTAX_ERROR: line 6:3: Unknown type: string

### ISSUE THREAD

**Issue by leel-LSC** [dbt-labs/dbt-utils#445]
### Describe the bug
when using dbt_utils.pivot on aws athena / presto engine, I get the following error: SYNTAX_ERROR: line 6:3: Unknown type: string
The issue is when casting the field_name as string during the operation: 

`cast('{{` col.column }}' as {{ dbt_utils.type_string() }}) as {{ field_name }}`

### Steps to reproduce
WITH sample AS (
    SELECT * FROM (VALUES ('strA', 1), ('strC', 2), ) AS account (name, test)
),
unpivot as (
  SELECT name, 
  CAST('test' as string) as field_name,
  CAST(test as double) as value
  FROM sample
  )
SELECT * from unpivot

### Expected results
name | field_name  | value
strA | test | 1.0
strB | test | 2.0

### Actual results
the operation fails with SYNTAX_ERROR: line 6:3: Unknown type: string

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.4

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: AWS Athena)

**The output of `dbt --version`:**
installed version: 0.21.0
   latest version: 0.21.0

Plugins:
  - postgres: 0.21.0
  - athena: 0.21.0
  - redshift: 0.21.0
  - bigquery: 0.21.0

### Additional context
changing the code from `as string` to `as varchar` resolves the issue.

WITH sample AS (
    SELECT * FROM (VALUES ('strA', 1), ('strC', 2)) AS account (name, test)
),
unpivot as (
  SELECT name, 
  CAST('test' as VARCHAR) as field_name,
  CAST(test as DOUBLE) as value
  FROM sample
  )
select * from unpivot

support for aws athena would be great.

### Are you interested in contributing the fix?
no

**Comment by joellabes** [comment]
@leel-LSC Thanks for raising this and for the thorough writeup! 

dbt-utils' scope only extends to the "core four" adapters - Postgres, BigQuery, Redshift and Snowflake. For other adapters, it's common to build a "shim" package (e.g. https://github.com/dbt-msft/tsql-utils) which implements database-specific behaviour. 

There are a couple of options for you: 
1. I _think_ that if the Athena adapter extended both PostgresAdapter as well as SQLAdapter [here](https://github.com/Tomme/dbt-athena/blob/master/dbt/adapters/athena/impl.py#L13), as [Redshift does](https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/adapters/redshift/impl.py#L24) that you would get the Postgres version of string (which _is_ `varchar`) "for free". You could open an issue on the dbt-athena repo suggesting this
2. You could use the existing macro's code as inspiration, copying it into your project and modifying it to work correctly on Athena
2. Assuming you first do `2`, over time this could develop into a shim package which collates all of the Athena-specific implementations of these macros. 

For now, I'm going to close this out - hopefully that puts you on the right path though.
