### ISSUE TITLE
.gitignore in v0.8.0 includes dbt_modules instead of dbt_packages

### ISSUE THREAD

**Issue by jkg1595** [dbt-labs/dbt-utils#461]
### Describe the bug
v1.0.0 of dbt uses dbt_packages instead of dbt_modules.  .gitignore in v0.8.0 of dbt-utils still references dbt_modules.  Does that need to be updated?

**Comment by joellabes** [comment]
@jkg1595 good spotting! I'd welcome a PR to fix this 🔨

**Comment by nkyuray** [comment]
Hi @joellabes 

If @jkg1595 will not take this, I would be happy to work on.
