### ISSUE TITLE
README.md - coalesce should say concatentation

### ISSUE THREAD

**Issue by stannnman** [dbt-labs/dbt-utils#470]
### Describe the bug

README.md
Schema tests -> unique_combination_of_columns()

"passing the unique test a coalesce of the columns"
should say
"passing the unique test a concatenation of the columns"

### Steps to reproduce
n/a

### Expected results
"passing the unique test a concatenation of the columns"

### Actual results
"passing the unique test a coalesce of the columns"

### Screenshots and log output
n/a

### Are you interested in contributing the fix?
Yes

**Comment by joellabes** [comment]
@stannnman always happy to see PRs related to documentation! Feel free to rework it 🙏

**Comment by joellabes** [comment]
This has been fixed!
