### ISSUE TITLE
Create an approx_product() macro to multiply row values in a provided column

### ISSUE THREAD

**Issue by jayziic** [dbt-labs/dbt-utils#471]
### Describe the feature
A new dbt_utils macro for the approximate product of values within a specified column. 
ref: https://blog.jooq.org/how-to-write-a-multiplication-aggregate-function-in-sql/

#### Code suggestion: 
<details> 

```
{% macro create_approx_product() %}

-- approx_product(product_column)

create or replace function {{ target.database }}.{{ target.schema }}.approx_product(
  product_column decimal
)
  returns decimal
  strict  -- returns NULL on NULL input
  immutable  -- when called with the same inputs, returns the same results
  as
  $$

  case 
    -- when zero value in product column: modify as cannot take logarithm of a zero value, but if zero is here then final value will be 0
    when sum(case when product_column = 0 then 1 end) > 0 then 0
    -- when negative value in product column: modify as cannot take logarithm of a negative number, if uneven number of records with -ve sign then return -1
    when sum(case when product_column < 0 then -1 end) % 2 < 0 then -1
    -- else consider it the original exp sum log function logic multiplied by 1
    else 1 
  end 
  -- exclude zero values from the actual aggregation that uses EXP() and LN() via NULLIF()
  -- deal with negative values via ABS()
  * exp(sum(ln(abs(nullif(product_column, 0)))))::decimal 

  $$
  ;
{% endmacro %}
```

```
with test_cases as (
  select
    test_description,
    {{ target.database }}.{{ target.schema }}.approx_product(product_column) as return_values
  from (
    values
      ('test1_all_negatives', -2),
      ('test1_all_negatives', -3),
      ('test1_all_negatives', -4),
      ('test2_zero_value', 2),
      ('test2_zero_value', 3),
      ('test2_zero_value', 0),
      ('test3_all_positives', 2),
      ('test3_all_positives', 3),
      ('test3_all_positives', 5),
      ('test4_even_negatives_one_positive', -2),
      ('test4_even_negatives_one_positive', -3),
      ('test4_even_negatives_one_positive', 5),
      ('test5_one_negative', -2),
      ('test5_one_negative', 3),
      ('test5_one_negative', 5)
  ) as t (test_description, product_column)
  group by 1
)
select
  *, 
  case 
    when test_description = 'test1_all_negatives' then -24 -- approx_product should end up with -23.999999999999993
    when test_description = 'test2_zero_value' then 0 
    when test_description = 'test3_all_positives' then 30 
    when test_description = 'test4_even_negatives_one_positive' then 30
    when test_description = 'test5_one_negative' then -30
  end as expected_value
from test_cases
where abs(return_values - expected_value) > 0.01
```
</details>

### Describe alternatives you've considered
Alternatives considered 
* pivot and manually multiply columns (which is more cumbersome)
* manually code the above macro using the same logic

### Additional context
This feature is not database specific afaik. 
But i am unsure how to implement an `PARTITION BY` condition if required, by including it in the SUM() function. 

### Who will this benefit?
Anyone who wishes to calculate combinations, or multiply row values. 
Likely to be most beneficial to bespoke use cases, and people familiar with Excel formulas. 
People of all downstream SQL languages will benefit as the EXP(), LN() and SUM() functions tend to be universal in language but not this approx_product() function. 

### Are you interested in contributing this feature?
yes!

**Comment by joellabes** [comment]
Hi @jayziic! Thanks for opening this and providing the sample code + tests! 

One comment to make first: dbt_utils creates macros that generate SQL for use inside of a standard query, not macros that create user-defined functions. It looks like this macro could be created as a SQL generator, so I'd be happy to bring it through! 

Likewise, the tests should be implemented as input and expected output seeds - have a look how `star` is tested for examples ([model](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/test_star.sql), [input](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/data/sql/data_star.csv), [expected output](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/data/sql/data_star_expected.csv), [test definition](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/schema.yml#L109-L112))

If you wanted to take a swing at this, I'd be happy to have a look at a PR 🎉
