### ISSUE TITLE
Support for functions respecting require_partition_filter

### ISSUE THREAD

**Issue by nishantnathhoney** [dbt-labs/dbt-utils#475]
### Describe the feature
Tests should allow respecting tables specified with `require_partition_filter = true`

Onus of veracity of supplied arguments should be on user.

1.  An easy workaround is simply allowing users to specify the `<partitionField>`.
    - If `partition_field` is specified, append `WHERE <partitionField> IS NOT NULL`
    - If unspecified - no action taken
2. A customizable workaround is to allow users to specify a custom filter like `partition_filter = <partitionField> >= <date1> and <partionField> < <date2>` which can be appended during compilation step with `WHERE`.

Considering these tests would most likely never be run on specific date ranges only (option 2) is probably not a good idea.

### Describe alternatives you've considered
- Removing the `require_partition_filter = true` from source model is counterproductive

### Additional context
Google BigQuery specific feature

**Existing Compiled Output:**
```
with validation_errors as (

    select
        <col1>, <col2>
    from `project.dataset.table`
    group by <col1>, <col2>
    having count(*) > 1

)

select *
from validation_errors
```

**Proposed Compiled Output:**
```
with validation_errors as (

    select
        <col1>, <col2>
    from `project.dataset.table`
    WHERE <partitionField> IS NOT NULL    <----- New Condition added
    group by <col1>, <col2>
    having count(*) > 1

)

select *
from validation_errors
```

### Who will this benefit?
All BigQuery users relying on `require_partition_filter` features

**Comment by joellabes** [comment]
@nishantnathhoney thank you for opening this! 

Disclaimer: I learned about this functionality about 10 minutes ago, so forgive any ill-informed questions...

My understanding is that these are normal where clauses, right? Since dbt v0.20 or so, any test has been able to get a where clause "for free": 

```
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - dbt_utils.expression_is_true:
              expression: "a + b = c"
              where: "partition_column = 'something'"
```

which then gets rendered to 
```

with meet_condition as (
    select * from (select * from ANALYTICS.dbt_jlabes.my_first_dbt_model where partition_column = 'something') dbt_subquery where 1=1
)
```

I'm going to close this because I think that would solve your use case without needing to implement partition filtering in every single test - let me know if I've misunderstood though!

**Comment by joellabes** [comment]
Ah OK! If you want to set a default behaviour for all tests, that'd be outside the scope of dbt utils. 

There's a couple of options: 
- Your goal sounds very similar to https://github.com/dbt-labs/dbt-core/issues/3841, except that you're looking to add a default where clause as opposed to a default severity. They should be able to be achieved in the same way - override any tests you want to behave this way 
- Given that this is BQ-native behaviour, it's reasonable to advocate for a first-class implementation for everyone. If you wanted to open an issue about this on https://github.com/dbt-labs/dbt-bigquery, I think the team would be interested in checking it out.

**Comment by nishantnathhoney** [comment]
Sounds about right, I'll open an issue in dbt-biquery for further discussion. Thanks 😄
