### ISSUE TITLE
Use "generic test" naming style instead of "schema test"

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#485]
Schema tests were renamed to generic tests - the readme and folder structures should update to reflect that. 

- readme headers and anchor links
- body of readme (the "this schema test..." text under each test. Even better: drop that part and say something like "Assert the that two relations have the same number of rows"
- folder path for the schema tests

### Are you interested in contributing the fix?
Yes

**Comment by b-moynihan** [comment]
Hi @joellabes, I'm interesting in taking a look at working on this issue. I see it was opened in late Jan, just confirming this is still relevant and there's no existing PR addressing this? :)

**Comment by dbeatty10** [comment]
Fixed by https://github.com/dbt-labs/dbt-utils/pull/521
