### ISSUE TITLE
`dbt_utils.star` macros bug

### ISSUE THREAD

**Issue by mc-introhive** [dbt-labs/dbt-utils#506]
### Describe the bug

I created an issue in `sqlfluff` [repo](https://github.com/sqlfluff/sqlfluff/issues/2712), because `sqlfluff` refuses to recognize `dbt_utils` macros. More details (steps to reproduce, expected results, actual restuls, logs, system info, etc.) can be found in this closed issue in `sqlfluff` However, it turns out when run `sqlfluff lint -v`, when it hits `dbt_utils.star`, specifically this block https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql#L11 it failed to recognize the `execute` flag. But it should've been recognized because `sqlfluff` does compile dbt projects which will trigger an `execute` flag to be true. 

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

### Are you interested in contributing the fix?
Yup :)

**Comment by joellabes** [comment]
@mc-introhive Thanks for expressing interest in contributing a fix - I think will be as simple as changing https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql#L11 to `{{ return('*') }}` 👍

**Comment by mc-introhive** [comment]
Oops, I don't have permission to push branches :)

**Comment by joellabes** [comment]
@mc-introhive you can contribute by forking the project and then opening a PR back to the main project. 

If you're new to open source, I recommend using the GitHub desktop app as it will guide you through the workflow of cloning a repo with the purpose of contributing back to it. For a change of this size, you could also fork it in the web browser, change the character in the web editor, and then open a PR from the prompt after that. 

Let me know if you need a bit more of a nudge in the right direction - happy to help get people set up to contribute!

**Comment by mc-introhive** [comment]
Yeah, I'm quite new to the open-source contribution process, and thank you for pointing me to the right direction!

Is this what I'm supposed to do? 
1. I already forked the repo
2. created a PR (as you can see above), but to my own forked repo
3. After testing that and merge it into my own forked `main` branch, then I can click that `contribute` button to open up a PR for this original repo?

Am I on the right track?

<img width="1531" alt="Screen Shot 2022-03-10 at 15 53 57" src="https://user-images.githubusercontent.com/97176808/157752646-926fbac2-e559-4feb-ad11-2690329f0d4d.png">
