### ISSUE TITLE
Add condition parameter to get_column_values

### ISSUE THREAD

**Issue by djbelknapaw** [dbt-labs/dbt-utils#511]
### Describe the feature
It would be handy if `get_column_values` had a condition that would stick a `where <condition>` in the query. I've got a big table and only want values from a subset of records.

### Describe alternatives you've considered
* Writing a macro of my own that grabs specifically what I want.
* Pointing the get_column_values macro at a model that filters records for me, which leads to models that exist just for the filter.

### Who will this benefit?
I have a big tall table with a whole bunch of key-value pairs that belong to different record types. I want to use `pivot` with a list of columns, but I want that list of columns to be specific to just one record type at a time.

Or more generally, maybe you want column values that only come from non-soft-deleted records (or myriad reasons why you might just want a subset).

### Are you interested in contributing this feature?
I can probably contribute to this if you're open to this change.

**Comment by epapineau** [comment]
Looks like I just opened a redundant issue #582. I'd be happy to tackle this.
