### ISSUE TITLE
Add to_condition to relationships_where documentation

### ISSUE THREAD

**Issue by macklin-fluehr** [dbt-labs/dbt-utils#514]
### Describe the bug

relationships_where documentation currently only documents from_condition. to_condition is undocumented

### Steps to reproduce
read the readme for relationships_where

### Expected results
to_condition is in the example for relationships_where

### Actual results
to_condition is not there

### Screenshots and log output
<img width="880" alt="Screen Shot 2022-03-09 at 4 07 58 PM" src="https://user-images.githubusercontent.com/35469749/157536328-7a676b53-8cec-4c78-af17-6354a8fa7e62.png">

### System information
N/A

**Which database are you using dbt with?**
N/A

**The output of `dbt --version`:**
N/A

### Additional context
N/A

### Are you interested in contributing the fix?
no

**Comment by joellabes** [comment]
Thanks @macklin-fluehr, just added this to the readme 🚀
