### ISSUE TITLE
feat: add order_by macro

### ISSUE THREAD

**Issue by pcorbel** [dbt-labs/dbt-utils#523]
### Describe the feature
An order_by macro

### Describe alternatives you've considered
Other solution is to manually order by in the query

### Additional context
It should be ANSI compliant

### Who will this benefit?
All dbt_utils users who uses `group_by` should be also be allowed to use `order_by`

### Are you interested in contributing this feature?
Yes, I'am interested

**Comment by pcorbel** [comment]
Associated PR: https://github.com/dbt-labs/dbt-utils/pull/524

**Comment by joellabes** [comment]
Hey @pcorbel - I didn't realise you'd also created an issue in advance of the PR, so I've replied on the PR directly ⭐
