### ISSUE TITLE
BQ get_relations_by_pattern gives `Unexpected string literal "table_type"` error

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#536]
### Describe the bug
[From the community Slack](https://getdbt.slack.com/archives/CMZ2V0X8V/p1649381252167749)
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7335046/162346699-74778c3a-4bd9-49e0-bac9-2aec81cdbb23.png">
 

### Expected results
Not to get an error

### Actual results
An error `Unexpected string literal "table_type"`

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt Cloud 1.0
```

### Additional context
This is my fault - https://github.com/dbt-labs/dbt-utils/pull/525 changed this, and the original author called out that quoting the column caused this error. Unfortunately, at the last moment I re-quoted it to avoid a Snowflake issue (https://github.com/dbt-labs/dbt-utils/issues/484#issuecomment-1089274595)

This can be handled by creating a BQ-specific override that _doesn't_ quote the resulting column. 

### Are you interested in contributing the fix?
Extremely

**Comment by cambalzer** [comment]
Thanks @joellabes. Confirming that the two affected models are using that macro: get relations by pattern
