### ISSUE TITLE
Investigate why the BQ integration test didn't fail for quoted column name

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#540]
### Describe the bug
We caused #536 (fixed in #537) because of [this change](https://github.com/dbt-labs/dbt-utils/pull/534/commits/72a5150f7107b1d24905201a7c2d1e3d78c6418e#diff-78b95692b8987e2694e4d6e1c6ce521ea740b59ddb2a51d9ff6215f0b5502aa6) which was designed to avoid a similar issue in reverse from Snowflake (that it would have uppercased the column and failed to match in jinja, see #484.

Looking at the [Circle logs for the job](https://app.circleci.com/pipelines/github/dbt-labs/dbt-utils/820/workflows/38f90d3f-9676-4d0a-bd74-814e20a444be/jobs/2567), it turns out that the table did error, but:
- the subsequent dbt test invocation completed with exit code 0 (i.e. only the last step's outcome matters to Circle)
- the dbt test invocation succeeded _because_ even though the table failed to build, we don't generate unique schemata for each PR so it would have found an old copy of the table from a prior CI run. 
- Related: the fact that all PRs share a common schema also means that if two people push up commits at the same time, dbt will stop all over each other's tests and you get weird errors. This also happens if the same person commits back to back, but that's less of an issue IMO (I don't think we need a custom schema for every git commit for example). 

### Steps to reproduce
- Cause a failure in an earlier stage of an invocation, that doesn't impact the final `dbt test` invocation ([see here](https://github.com/dbt-labs/dbt-utils/blob/33299334a305d0acb99ebee8cc2eb6eb2ba5ca31/run_test.sh#L25-L31))

### Expected results
CI to fail, because something didn't work

### Actual results
No error because dbt test (the final step) still succeeds

### Screenshots and log output
Linked above, but in case Circle has thrown away the logs by the time we get to this: [utils-bq-logs.txt](https://github.com/dbt-labs/dbt-utils/files/8455238/utils-bq-logs.txt)

**Comment by jasnonaz** [comment]
This is an awesome investigation into possible solutions here - thank you @dbeatty10!!!

Feels like if we could get this working off of dbt build alone that would be a tremendous win. Two things to think through there on how we might mitigate the downside of it not working with `insert-by-period`.

- In the [future of utils ](https://github.com/dbt-labs/dbt-utils/discussions/487) discussion, Joel wrote about moving the insert_by_period materialization into the [experimental feature](https://github.com/dbt-labs/dbt-labs-experimental-features) repo. If we were to go ahead and do that then we wouldn't have to worry about tests for insert by period.
- You've probably already thought of this but would the insert-by-period tests work on a dbt build --full-refresh?

Those points aside, curious to hear which one you think would be best to move forward on.

**Comment by dbeatty10** [comment]
I'm interested in pursuing `command || exit 1` as our initial response and then queue `dbt build`, etc as follow-ups.

Rationale:
- minimally invasive and straight-forward
    - only requires adding ` || exit 1` suffix to 5 lines of code
- solves the immediate problem
    - already tested it out in my local environment
- moving us in the right direction and also completely reversible 
    - it doesn't prevent us from pursuing the other ideas like `dbt build`, etc as the next logical steps to take

**Comment by jasnonaz** [comment]
Beautiful - let's do it!
