### ISSUE TITLE
`surrogate_key` macro is not adding the || with concat in dbt Version > 0.20.1

### ISSUE THREAD

**Issue by ArunT317** [dbt-labs/dbt-utils#556]
### Describe the bug
With the dbt upgrade to v1.0.0/1.0.4/1.0.5 surrogate key macro is not generating the appropriate sql code.

### Steps to reproduce
(1) Create a model with surrogate key macro for more than two columns.
(2) dbt run will fail because of missing '||' operator inside the concat statements.

### Expected results
Properly formatted sql is expected with || symbol inside the concat statement.
![image](https://user-images.githubusercontent.com/80901524/164757317-5038be4a-fae9-486d-97fd-6d7e190e92ed.png)

### Actual results
![image](https://user-images.githubusercontent.com/80901524/164757412-b0931f60-1589-487d-8890-d5d224d91dee.png)

### Screenshots and log output
Added above

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.0.4
```

**Comment by ArunT317** [comment]
I guess the issue is most likely with the concat macro which is used inside surrogate key macro.
It is not appending the `||` operator

**Comment by judahrand** [comment]
This seems like it is actually quite a significant issue...

I'd imagine a common use case for `surrogate_key` is to produce a key for an incremental model (since before 1.1.0 you could only use a single column). If the way this key is calculated has changed and people don't do a 'full-refresh' on their incremental models then they'll end up with duplicate data!  In some cases a 'full-refresh' might not even be that feasible. 

I think this should be fixed ASAP and the community notified of the potential issue.

**Comment by judahrand** [comment]
Though, actually, this looks like the new SQL will just fail - right?

**Comment by rcaddell** [comment]
I use this macro pretty frequently also via dependency on dbt_expectations, also using snowflake and do not experience this issue.  Is anyone else out there on Snowflake able to reproduce?


![dbt_version](https://user-images.githubusercontent.com/64412616/169294316-119b8dd6-26ec-40a8-8b2c-c74d9b7554b1.png)

![packages](https://user-images.githubusercontent.com/64412616/169294410-53edfcbc-f200-4536-ad09-27b1a0f32c97.png)

![w_macro](https://user-images.githubusercontent.com/64412616/169294427-947477d8-2934-43c5-aaeb-30b58e3d2941.png)

![compiled](https://user-images.githubusercontent.com/64412616/169294440-793c890c-2e09-478e-bbae-c80a414ffb46.png)

**Comment by joellabes** [comment]
Hey all, 

I was unable to reproduce this on dbt Core 1.2.0, using dbt utils 0.9.1. 

The code 
```
select {{ dbt_utils.surrogate_key(['a', 'b'])}}
```
on Snowflake renders to 
```
md5(cast(coalesce(cast(a as TEXT), '') || '-' || coalesce(cast(b as TEXT), '') as TEXT))
```

which looks correct to me! 

Are you still observing this? if so can you confirm:
- which version of dbt Core + dbt utils you are using
- which warehouse you are using
- the specific code you are trying to render, and what result you see?
