### ISSUE TITLE
Store compatibility matrix within repo (instead of Google Sheets)

### ISSUE THREAD

**Issue by bbrewington** [dbt-labs/dbt-utils#565]
### Describe the feature
Store compatibility matrix in repo (is currently in Google Sheet, linked from README)

### Describe alternatives you've considered

* https://github.com/Linkurious/documentation-resources/blob/master/compatibility-matrix/compatibility-matrix.md
* [LayZeeDK](https://gist.github.com/LayZeeDK)/[angular-compatibility.md](https://gist.github.com/LayZeeDK/e1b5b6e0599802c671b564a62d1261eb)
* Could also publish it as a PDF printout saved in github, but that would probably add unnecessary data

### Additional context
I'm not able to access Google Sheets while on my company network because of a security policy - makes configuring package versions in packages.yml file annoying (have to use personal laptop instead)

### Who will this benefit?
1. Anyone on a network blocked from Google Sheets
2. For maintainers, after the compatibility info is saved within the repo, they'll be able to see it in local cloned version

### Are you interested in contributing this feature?
Sure!  Have an idea of how to start, and would probably need some design review, but glad to knock it out

**Comment by dbeatty10** [comment]
Thanks for thinking of this, @bbrewington! 🧠 

How do you use the chart? Start with a version of dbt-core and find compatible versions of dbt-utils? Or the other way around?

Messed around with some options (generally representative, but non-exhaustive):
1. Checkmarks - dbt-core as rows
1. Ones and zeros - dbt-utils as rows
1. Terse summary - dbt-core first
1. Terse summary - dbt-utils first

The utility of each option will definitely be affected by which use case(s) to prioritize.
All have their columns and rows haver version numbers ordered greatest to least.

Do you have a preference?

## Checkmarks - dbt-core as rows

| **dbt-utils \ dbt-core** | **0.8.2** | **0.8.1** | **0.8.0** | **0.7.6** | **0.7.5** | **0.7.4** | **0.7.3** | **0.7.2** | **0.7.1** | **0.7.0** | **0.6.6** | **0.6.5** | **0.6.4** | **0.6.3** | **0.6.2** | **0.6.1** | **0.6.0** | **0.5.1** | **0.5.0** | **0.4.1** | **0.4.0** | **0.3.0** | **0.2.5** |
|:------------------------:|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| 1.0.x                    |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.21.1                   |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.21.0                   |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.20.2                   |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.20.1                   |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.20.0                   |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |           |           |           |           |
| 0.19.2                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |
| 0.19.1                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |
| 0.19.0                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |           |           |           |           |           |           |           |
| 0.18.2                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |         ✅ |         ✅ |         ✅ |           |           |
| 0.18.1                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |         ✅ |         ✅ |         ✅ |           |           |
| 0.18.0                   |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |         ✅ |           |         ✅ |         ✅ |         ✅ |           |           |
| 0.17.2                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |
| 0.17.1                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |
| 0.17.0                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |         ✅ |         ✅ |           |           |
| 0.16.1                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |
| 0.16.0                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |
| 0.15.3                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |
| 0.15.2                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |
| 0.15.1                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |         ✅ |
| 0.15.0                   |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |           |         ✅ |

## Ones and zeros - dbt-utils as rows
| **dbt-utils version** | **1.0.x** | **0.21.1** | **0.21.0** | **0.20.2** | **0.20.1** | **0.20.0** | **0.19.2** | **0.19.1** | **0.19.0** | **0.18.2** | **0.18.1** | **0.18.0** | **0.17.2** | **0.17.1** | **0.17.0** | **0.16.1** | **0.16.0** | **0.15.3** | **0.15.2** | **0.15.1** | **0.15.0** |
|-----------------------|-----------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|
| 0.8.2                 |         1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.8.1                 |         1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.8.0                 |         1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.6                 |         1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.5                 |         1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.4                 |         1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.3                 |         0 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.2                 |         0 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.1                 |         0 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.7.0                 |         0 |          0 |          0 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.6                 |         0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.5                 |         0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.4                 |         0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.3                 |         0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.2                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.1                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.6.0                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.5.1                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.5.0                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.4.1                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.4.0                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |          0 |          0 |          0 |          0 |          0 |          0 |
| 0.3.0                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          0 |
| 0.2.5                 |         0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          1 |          1 |          1 |          1 |          1 |          1 |

## Terse summary - dbt-core first

| dbt-core |           dbt-utils          |
|:--------:|:----------------------------:|
| 1.0.x    |                0.7.4 - 0.8.2 |
| 0.21.1   |                0.7.1 - 0.7.6 |
| 0.21.0   |                0.7.1 - 0.7.6 |
| 0.20.2   |                0.7.0 - 0.7.6 |
| 0.20.1   |                0.7.0 - 0.7.6 |
| 0.20.0   |                0.7.0 - 0.7.6 |
| 0.19.2   |                0.6.3 - 0.6.6 |
| 0.19.1   |                0.6.3 - 0.6.6 |
| 0.19.0   |                0.6.3 - 0.6.6 |
| 0.18.2   | 0.4.0 - 0.5.0; 0.6.0 - 0.6.6 |
| 0.18.1   | 0.4.0 - 0.5.0; 0.6.0 - 0.6.6 |
| 0.18.0   | 0.4.0 - 0.5.0; 0.6.0 - 0.6.6 |
| 0.17.2   |                0.4.0 - 0.5.1 |
| 0.17.1   |                0.4.0 - 0.5.1 |
| 0.17.0   |                0.4.0 - 0.5.1 |
| 0.16.1   |                0.2.5 - 0.3.0 |
| 0.16.0   |                0.2.5 - 0.3.0 |
| 0.15.3   |                0.2.5 - 0.3.0 |
| 0.15.2   |                0.2.5 - 0.3.0 |
| 0.15.1   |                0.2.5 - 0.3.0 |
| 0.15.0   |                        0.2.5 |

## Terse summary - dbt-utils first

| **dbt-utils version** | **dbt-core version** |
|-----------------------|----------------------|
| 0.8.2                 | 1.0.x                |
| 0.8.1                 | 1.0.x                |
| 0.8.0                 | 1.0.x                |
| 0.7.6                 | 0.20.0 - 1.0.x       |
| 0.7.5                 | 0.20.0 - 1.0.x       |
| 0.7.4                 | 0.20.0 - 1.0.x       |
| 0.7.3                 | 0.20.0 - 0.21.1      |
| 0.7.2                 | 0.20.0 - 0.21.1      |
| 0.7.1                 | 0.20.0 - 0.21.1      |
| 0.7.0                 | 0.20.0 - 0.20.2      |
| 0.6.6                 | 0.18.0 - 0.19.2      |
| 0.6.5                 | 0.18.0 - 0.19.2      |
| 0.6.4                 | 0.18.0 - 0.19.2      |
| 0.6.3                 | 0.18.0 - 0.19.2      |
| 0.6.2                 | 0.18.0 - 0.18.2      |
| 0.6.1                 | 0.18.0 - 0.18.2      |
| 0.6.0                 | 0.18.0 - 0.18.2      |
| 0.5.1                 | 0.17.0 - 0.17.2      |
| 0.5.0                 | 0.17.0 - 0.18.2      |
| 0.4.1                 | 0.17.0 - 0.18.2      |
| 0.4.0                 | 0.17.0 - 0.18.2      |
| 0.3.0                 | 0.15.0 - 0.16.1      |
| 0.2.5                 | 0.15.0                |

**Comment by bbrewington** [comment]
wow, thanks for putting all that together!

personally, I prefer option 4: Terse summary - dbt-utils first.  Since it expands vertically, it's going to scale better, and all the version ranges are contiguous, so it's both compact and clear

**Comment by joellabes** [comment]
Related: https://github.com/dbt-labs/hub.getdbt.com/issues/165 - if we could get this into the Hub, it would work for every package and it wouldn't need manual upkeep!

**Comment by bbrewington** [comment]
@joellabes anything additional required on this?  note that this PR (which fixed issue 165 linked above) was merged on 8/25: https://github.com/dbt-labs/hub.getdbt.com/pull/1799

**Comment by joellabes** [comment]
Nah I think we're done! Good spotting @bbrewington 🙏
