### ISSUE TITLE
Use `adapter.quote()` for get_table_types_sql

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-utils#572]
### Describe the feature
Use `adapter.quote()` instead of double-quotes or backticks within macros/sql/get_table_types_sql.sql (as described here 
https://github.com/dbt-labs/dbt-utils/pull/537#discussion_r845947638)

### Who will this benefit?
This will make things cleaner and more simple when macros are migrated for https://github.com/dbt-labs/dbt-core/issues/4813

**Comment by alla-bongard** [comment]
I am happy to pick this up!

**Comment by dbeatty10** [comment]
Awesome @alla-bongard !

The update would go in the following places:
- https://github.com/dbt-labs/dbt-utils/blob/77dcf2e609bd0528de51d2a30f1bd59110c1b12f/macros/sql/get_table_types_sql.sql#L11
- https://github.com/dbt-labs/dbt-utils/blob/77dcf2e609bd0528de51d2a30f1bd59110c1b12f/macros/sql/get_table_types_sql.sql#L21
- https://github.com/dbt-labs/dbt-utils/blob/77dcf2e609bd0528de51d2a30f1bd59110c1b12f/macros/sql/get_table_types_sql.sql#L30

For good measure, these could be optionally updated also:
- https://github.com/dbt-labs/dbt-utils/blob/77dcf2e609bd0528de51d2a30f1bd59110c1b12f/macros/sql/get_tables_by_pattern_sql.sql#L9-L10

**Note:** If the `bigquery__get_table_types_sql` implementation becomes identical to the `default__get_table_types_sql` one, then it should be removed altogether 🙏

**Comment by alla-bongard** [comment]
clear, and it was exactly what I did! a PR is on the way! :)

**Comment by dbeatty10** [comment]
🙌
