### ISSUE TITLE
reduce spacing in compiled sql

### ISSUE THREAD

**Issue by joevandyk** [dbt-labs/dbt-utils#58]
The compiled sql when using get_url_parameter looks like http://take.ms/UIEzL

We should probably use `{%- -%}` instead of `{% %}`

**Comment by drewbanin** [comment]
Thanks @joevandyk. I think the changes will need to happen here:
https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/cross_db_utils/split_part.sql
