### ISSUE TITLE
Enable `get_column_values` with CTEs

### ISSUE THREAD

**Issue by lmmentel** [dbt-labs/dbt-utils#600]
### Describe the feature

Currently I am not able to get over the limitation of `get_columns_values` that requires the `table` argument to exist as a table in db. It would be quite a lot easier to do use `pivot` if that wasn't the case. Right now I am not able to figure out who to pass a CTE to pivot, for example

```sql
with temp as (
    select count(name), year(date) as year_start from table1
    group by date
)
select 
{{ dbt_utils.pivot(year_start, dbt_utils.get_column_values(temp, year_start))}}
from temp
 ```

Right now if I try to do this I get

```
Runtime Error
  Compilation Error in model  (models/content/model.sql)
    'str object' has no attribute 'database'

    > in macro default__get_column_values (macros/sql/get_column_values.sql)
    > called by macro get_column_values (macros/sql/get_column_values.sql)
    > called by macro load_relation (macros/adapters/relation.sql)
    > called by model monthly_completed_pivot (models/content/monthly_completed_pivot.sql)
```

I believe it's due to the call to `load_relation`.

### Describe alternatives you've considered
Saving an intermediate model would help but any templating/automation capability is lost.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

**Comment by joellabes** [comment]
Hey @lmmentel, thanks for opening this - you're correct that get_column_values requires the object to exist in the database. 

I think overcoming it inside of the same macro would lead to a very confusing method signature - you'd have to have some indicator of whether you're passing in a Relation or a CTE, and then change the behaviour based on that. 

Instead, I would recommend that you use something like [get_query_results_as_dict](https://github.com/dbt-labs/dbt-utils#get_query_results_as_dict-source) and use its results in your query. 

In your example, you could do something like: 

```
{% set query_text %}
with temp as (
    select count(name), year(date) as year_start from table1
    group by date
)
{% endset %}

{% set col_values = dbt_utils.get_query_results_as_dict(query_text ~ " select year_start from temp") %}

{{ query_text }} --reuse in the body of the query as well

select 
{{ dbt_utils.pivot(year_start, col_values['year_start'] )}}
from temp
```

☝️  that is extremly freehanded and won't actually work, but hopefully gives you an idea of what I mean. 

For now I'm going to close this as it won't result in a direct change to the get_column_values macro, and I'm not _convinced_ that this is stable enough to set up as a separate macro (like `get_column_values_from_cte()`). But if you get it into a good state where it's broadly applicable without needing lots of fiddly work, I'd welcome either reopening this issue or starting a new one 🎟️.
