### ISSUE TITLE
Snowflake array subtract macro

### ISSUE THREAD

**Issue by samLozier** [dbt-labs/dbt-utils#609]
### Describe the feature

As far as I'm aware, snowflake can combine arrays, check for intersection and aggregate but it is not easy to subtract arrays using a built in function. I don't know if this behavior is the same in other databases, so this may not be broadly useful, but I have found a way to do this in Snowflake that may be useful as a utils function. 

### Describe alternatives you've considered

What worked for me was laterally flattening my array column, then doing a row-wise comparison to another set of values, nulling if it's in the other column. I then use qualify with array_agg to rebuild the array and return a table with the prior row count. 

This is outside of the patterns I've seen used in DBT utils so far, since I think it will only work as a CTE that gets joined back to the original dataset to replace an array column. 

### Additional context

This may not be broadly useful (I'm less familiar with the array features of other databases), but could be very helpful in Snowflake. 

For a real-world use case: I have a business name string column and want to remove common words. Prior to running the macro, I'd split the string on whitespace. 
```
id | biz_name  
1  | 'acme anvil corp'
```
```
common_words
('corp', 'inc', 'ltd')
```
I want the end result: 
```
id | biz_name
1 | 'acme anvil' 
```
My first pass at doing this, working for my own purposes: 
```
{% macro array_subtract(model, array1, array2) %}
(select
distinct
     {{ array1 }} as {{ array1 }}
, array_agg(c.value::string) within group ( order by INDEX asc ) over (partition by SEQ) as {{ array1 }}_SUB
from {{ model }},
     lateral flatten(input => {{ array1 }}) as c
where c.value::string not in {{ array2 }}
and {{ array1 }} is not null
qualify row_number() over (partition by SEQ order by INDEX asc ) = 1)
{% endmacro %}
```
In this instance array2 is a single list of values being passed in, not a column of arrays, though that would be a useful improvement. Probably just as simple as switching to array_intersect vs the "not in" syntax 

### Who will this benefit?

Useful for data cleaning, or really any situation where set subtraction with preserved order is desired. 

### Are you interested in contributing this feature?
I'd like feedback on my first pass above, but would be interested in taking it further if it seems like something that dbt_utils wants to adopt.

**Comment by samLozier** [comment]
Here's a second approach with the array_contains version
```
with sub as (select array_construct('acme', 'inc') as company
                  , array_construct('inc', 'corp') as common_words),

     deleted as (select distinct company                           as company
                               , array_agg(c.value::string) within group ( order by INDEX asc )
                                           over (partition by SEQ) as company_SUB
                 from sub,
                      lateral flatten(input => company) as c
                 where array_contains(c.value::string::variant, common_words) = false
                   and company is not null
                     qualify row_number() over (partition by SEQ order by INDEX asc ) = 1)


select *
from deleted
```

**Comment by joellabes** [comment]
@samLozier this is very cool! For it to join the dbt_utils family it'd need to be able to be implemented (either natively or by using other builtin functionality to emulate it) on at least the core four warehouses we support here. 

If you didn't want to do that work (which is fair!) I wonder whether you could turn it into a discussion post on our currently-badly-named developer repo: https://github.com/dbt-labs/docs.getdbt.com/discussions/categories/how-i-do-this

**Comment by samLozier** [comment]
Discussion created here: https://github.com/dbt-labs/docs.getdbt.com/discussions/1960 thanks for the feedback @joellabes
