### ISSUE TITLE
convert unix timestamp

### ISSUE THREAD

**Issue by jthandy** [dbt-labs/dbt-utils#61]
this works for redshift:

```
{% macro convert_unix_timesetamp(field_name) -%}
timestamp 'epoch' + {{field_name}} * interval '1 second'
{%- endmacro %}
```

would be great to have a cross-database compatible version.

**Comment by devrang** [comment]
Above micro will not work in redshift. this worked for me:
{% macro convert_unix_timestamp(field_name) -%}
timestamp 'epoch' + {{field_name}}/1000 * interval '1 second'
{%- endmacro %}

**Comment by Kalidaas23** [comment]
i think you can use this query directly to get the desired results
:
select
*,
timestamp 'epoch' + unixdate::INT * INTERVAL '1 second' as test
from {{ source("yourmodel","table_name")}}
