### ISSUE TITLE
unique_combination_of_columns should accept an optional where clause

### ISSUE THREAD

**Issue by epapineau** [dbt-labs/dbt-utils#610]
### Describe the feature
A where clause argument to only test `unique_combination_of_columns` on a subset of data

### Describe alternatives you've considered
Using the `where` clause on the generic unique tests. However, this does not work when I need to test multiple columns.

### Who will this benefit?
Myself & a client I am working with + anyone using `unique_combination_of_columns` 

### Are you interested in contributing this feature?

Yes~

**Comment by joellabes** [comment]
All tests get where for free nowadays! We discussed this on the PR

https://docs.getdbt.com/reference/resource-configs/where
