### ISSUE TITLE
Pivot Example Outdated / Incorrect

### ISSUE THREAD

**Issue by rankam** [dbt-labs/dbt-utils#611]
### Describe the bug
The example for pivots no longer works and hasn't for several years https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/pivot.sql#L17. This issue even says that the example will no longer work https://github.com/dbt-labs/dbt-utils/issues/153.

**Comment by dbeatty10** [comment]
@rankam Thank you for noticing this and creating an issue!

Do you know an example that _will_ work?
