### ISSUE TITLE
New macro: get_query_results_as_single_value

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#617]
### Describe the feature
It's common to need to pull a single value from a table or query and then use it somewhere else, but it's super clunky (example: @invinceyble's [Coalesce talk last year](https://youtu.be/OcCB7BxbxDY?t=618))
![image](https://user-images.githubusercontent.com/7335046/178889131-287e113f-2f89-4c15-a3ab-da05af17b446.png)

This is exactly the sort of thing that this package should abstract away! 

### Describe alternatives you've considered
Continuing to use lower-level macros (run_query, get_query_results_as_dict)

### Additional context
It should all just work! It's handled by dbt code which is already adapter aware. 

### Who will this benefit?
People who want to pull a single date/value/string and include it in a query for some reason. 

### Are you interested in contributing this feature?
Sure am!

**Comment by invinceyble** [comment]
great feature 🚀 also happy to contribute :D

**Comment by joellabes** [comment]
@invinceyble if you wanted to dive in we'd welcome your contribution! 

I think the main macro can basically just be that code snippet above, but should return `""` or some other sensible default when [`execute`](https://docs.getdbt.com/reference/dbt-jinja-functions/execute) is false (otherwise I think it will output `None` and/or fail?)

Then it would just be a case of adding some tests in the integration_tests folder which check it works correctly across various databases and datatypes. The input could be as basic as a one-row seed that has a column for each of datetime, string, int and float, and the output could be a model that does something with them and compares to another seed (have a poke around in the integration_tests folder for some examples, or we can give you extra pointers). 

With that said, we're changing to pytest in the near future - @dbeatty10 is that for everything, or just for testing stuff that is too hard to implement as dbt tests? 

Ofc if this sounds like more than you felt like taking on then let me know - no stress!

**Comment by dbeatty10** [comment]
Brilliant feature suggestion @joellabes and @invinceyble 🤩 

Please let me know anything I can do to assist.

Regarding testing: we will move `dbt_utils` fully onto this framework at some point, but not yet. So I'd recommend just implementing tests like the existing work in the [integration_tests](https://github.com/dbt-labs/dbt-utils/tree/ffddc493c176204ecee3c0a59565ac1cbcc6d94e/integration_tests) folder like Joel described.

(It's actually fairly straight-forward to port our current integration tests into that new framework, so doing it this way wouldn't incur a bunch of tech debt.)

**Comment by Maayan-s** [comment]
We actually have such util in Elementary:
https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/utils/run_queries/result_value.sql

I will be happy to contribute so more users could apply it when needed.

**Comment by joellabes** [comment]
@Maayan-s sure! happy for you to do so, as long as it comes with the same tests that I described above 👍

**Comment by CR-Lough** [comment]
Hey all, I didn't see any branches yet for the issue so I went ahead and [made this PR](https://github.com/dbt-labs/dbt-utils/pull/696).
