### ISSUE TITLE
[CT-546] dbt Utils Surrogate Key is not generating the appropriate SQL

### ISSUE THREAD

**Issue by ArunT317** [dbt-labs/dbt-utils#641]
### Describe the bug
We are making use of dbt utils surrogate key macro for hashed unique identifier generation. It is working as expected with the version 0.20.1 when i updated the dbt version to 1.0.0 (snowflake) and (1.0.4) dbt-core. This macro is not generating the required sql its missing the || symbol between the concat statements.

### Steps To Reproduce
(1) Create a model with dbt_utils Surrogate key macro.
(2) Run the model with the dbt version > 0.20.1

### Expected behavior
Well formed sql with proper concat statement is expected.

### Screenshots and log output
![image](https://user-images.githubusercontent.com/80901524/164755049-aa39a6a5-c05b-465c-a8ce-127f5568eb47.png)

### System information
**The output of `dbt --version`:**
```
1.0.4
```

**The operating system you're using:**

```
Windows
```

**The output of `python --version`:**

```
3.8.8
```

### Additional context
Tried the dbt_utils package version 0.7.6 && 0.8.4

**Comment by joellabes** [comment]
@ArunT317 sorry for the slow delay on this! Are you still seeing this problem on the latest version of dbt utils 0.8.6?

Can you please provide the actual query you’re trying to use? This query compiles and runs correclty for me: 

```
with a as (
    select 1 as field_a, 'acd' field_b
)

select 
    {{ dbt_utils.surrogate_key(['field_a', 'field_b']) }}, 
    field_a, 
    field_b
from a
```
