### ISSUE TITLE
dbt-utils v0.9.0 breaks semantic versioning

### ISSUE THREAD

**Issue by mikeskov** [dbt-labs/dbt-utils#658]
### Describe the bug
Dbt-utils v0.9.0 is not backward compatible with dbt versions prior to 1.2.0. This is a breaking change, and thus the major version should be bumped. 

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by joellabes** [comment]
Hi @mikeskov, the semver spec [says the following](https://semver.org/#spec-item-4) about version zero software:
>Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

We intend to ship dbt utils 1.0.0 later this year, at which point we will lock in the interfaces as required. 

I assume that the release broke your run this morning; I'm sorry about that! For version zero packages, we tend to recommend splitting the difference by pinning to a single minor version at a time (i.e. receive all patches but opt into minor versions on a case by case basis).
