### ISSUE TITLE
Remove deprecated table argument from pivot()

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#670]
### Describe the feature
We swapped from table to relation in a long-past version of dbt utils, and promised it would be deprecated one day. 
https://github.com/dbt-labs/dbt-utils/blob/fc8b083f07b72790234f3227df40c4f54dd60c38/macros/sql/unpivot.sql#L21-L28
That day has come. 

This looks like: 
- Removing the table parameter
- Removing the checking for `table`, as well as checking for both `table` and `relation`. 
- Remove the [test_unpivot_original_api](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/sql/test_unpivot_original_api.sql) test
- The remaining tests should continue to pass 

### Who will this benefit?
Future users of this macro, who won't have conflicting and confusing documentation. Lovers of clean code

### Are you interested in contributing this feature?
Leaving it for a community member who wants to get into OSS contributions!

**Comment by ethanotran** [comment]
Can I work on this one? Looking for my first open source contribution.

**Comment by joellabes** [comment]
> Can I work on this one? Looking for my first open source contribution.

@ethanotran it looks like Miles might have already done some work on this one I'm sorry! I'm on mobile so I can't see exactly, or whether there's any others from the crop I opened earlier this week that are unclaimed. If you do find one, feel free to assign it to yourself 👍
