### ISSUE TITLE
Create a new safe divide cross db macro

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-utils#679]
### Describe the feature
I want to add a "safe divide" cross db macro (like [DIV0](https://docs.snowflake.com/en/sql-reference/functions/div0.html) in snowflake) to prevent errors when dividing by 0. 

### Who will this benefit?
Package developers - we're currently using nullif() on the denominator in dbt_project_evaluator package and would like to replace this with a simple safe divide macro. 

### Are you interested in contributing this feature?

Yes. I, @angelica-lastra, and @deanna-minnick will be collaborating on this!

**Comment by joellabes** [comment]
We talked about this internally - excited to see it come together!
