### ISSUE TITLE
Remove obsolete condition argument from expression_is_true

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#695]
### Describe the feature
In #691, @elyobo pointed out:
> why does `expression_is_true` have condition then? Doesn't `where` make it redundant?

And is quite right! 1.0 is a good place to make this breaking change. 

### Describe alternatives you've considered
Leaving it as-is, since we're coming in hot to the 1.0 release date. Since we're fully removing the `not_null_where` and `unique_where` tests, this is just another similar process.

### Who will this benefit?
- People who enjoy consistent APIs
- People who don't want to get confused by legacy behaviour

### Are you interested in contributing this feature?
Nope, but I'd welcome a community contribution (targeting the `utils-v1` branch)!

**Comment by joellabes** [comment]
Resolved by #700

**Comment by elyobo** [comment]
Thanks @miles170!
