### ISSUE TITLE
Source code link of insert_by_period is broken

### ISSUE THREAD

**Issue by liu431** [dbt-labs/dbt-utils#703]
### Describe the bug

On the README page (https://github.com/dbt-labs/dbt-utils#insert_by_period-source), the source code link is https://github.com/dbt-labs/dbt-utils/blob/main/macros/materializations/insert_by_period_materialization.sql and it doesn't exist when I opened it. I also could not seem to find it on this repo.

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by joellabes** [comment]
Hi @liu431, this materialization is not going to be part of dbt utils from version 1.0, coming later this month. It has been removed from the `main` branch but is still in v0.9.2, the final shipping version prior. 

I would recommend you install it from its new home in our experimental features repo: https://github.com/dbt-labs/dbt-labs-experimental-features/blob/main/insert_by_period/README.md#installation
