### ISSUE TITLE
equality test with where config

### ISSUE THREAD

**Issue by pettersoderlund** [dbt-labs/dbt-utils#704]
### Describe the bug
I would like to limit the rows compared in dbt_utils.equality test with a where clause.  

### Steps to reproduce

Create two models with the same set of columns. Configure equality test with where configuration - in this case a date limitation. 

`
version: 2

models:
  - name: model_v2
    tests:
      - dbt_utils.equality:
          compare_model: ref('model_v1')
          where: "dt_date > DATE_ADD(current_date('Europe/Stockholm'), INTERVAL -1 DAY)"
`

### Expected results

The equality test executed with the where clause added to both "model" and "compare_model".   

### Actual results
Compilation error 

### Screenshots and log output
Compilation Error in test dbt_utils_equality_model_v2_ref_model_v1_ (models/model_v2.yml)
11:48:56    Macro test_equality expected a Relation but received the value: (select * from `project`.`dataset`.`model_v2` where dt_date > DATE_ADD(current_date('Europe/Stockholm'), INTERVAL -1 DAY)) dbt_subquery
11:48:56    
11:48:56    > in macro _is_relation (macros/cross_db_utils/_is_relation.sql)
11:48:56    > called by macro default__test_equality (macros/generic_tests/equality.sql)
11:48:56    > called by macro test_equality (macros/generic_tests/equality.sql)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6
  - package: mjirv/dbt_datamocktool
    version: 0.2.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.1
  - latest:    1.3.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.1.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context

It seems the check not working is https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equality.sql#L23

My understanding of the check is to make sure of the later use of adapter.get_columns_in_relation will work. 

My guess is that the most important part that the where config is added is in the CTEs named a and b.  

### Are you interested in contributing the fix?

Sure - would be great with some hints on where to start

**Comment by joellabes** [comment]
Hi @pettersoderlund, sorry for the delay here! 

The where clause attached to a test is only ever applied to the `model`. 

With that said, I think that what you've found is a different bug, as I think error would trigger for _any_ where clause (i.e. the issue isn't that it's not spanning both tables). 

It would make sense to solve that by moving the is_relation check into here, as it's the only place that would cause a problem: 
https://github.com/dbt-labs/dbt-utils/blob/84cf0f2971f5bf539b06c42373a5e80b59ba7047/macros/generic_tests/equality.sql#L30-L33

I guess we could also add a `compare_model_condition` parameter to this test, to accompany the `where` param. I'd be happy to review a PR in that vein if you wanted to open one.

**Comment by pettersoderlund** [comment]
Hi @joellabes !
Thank you for the feedback :) 

The error does exist for any where clause - that is correct! 

However it does not really solve the problem moving the is_relation check to inside the check for compare_columns -- we'd still have the error if columns are not specified - this is not good enough in my opinion. 

A nice solution would be if we could get the Relation _without_ the subquery caused by the where config -- in that case we could pass Relation to get_columns_in_relation.

After doing some digging into this we found this thread where you and others seem to discuss a similar matter: https://getdbt.slack.com/archives/C01UM2N7814/p1647510807608879 

From reading the slack thread there seems not to be big hopes on getting the not-modified-relation when using where config. Would you say it is a better approach to instead add two parameters to equality: where_clause, compare_model_where_clause - not using test config where at all?

**Comment by james-johnston-thumbtack** [comment]
I created a couple different pull requests, #1001 and #1002, which I think would resolve the issue in this GitHub issue.  Basically they carry out the improvements that @joellabes proposed at https://github.com/dbt-labs/dbt-utils/issues/704#issuecomment-1341904751
