### ISSUE TITLE
Surrogate key macro does not work with case sensitive column names

### ISSUE THREAD

**Issue by villar1** [dbt-labs/dbt-utils#711]
### Describe the bug
Our database is case sensitive and we need to use quotation marks. Thus I cannot to use the surrogate key macro, since the result is always the given column name without quotation marks. I have also tried specifying in the model.yml to use quotation marks for the specific column but it does not work.

### Steps to reproduce
This
```
<{{ dbt_utils.surrogate_key (["idNumber"]) }} as "idNumber">
```
Compiles into this
```
<md5(cast(coalesce(cast(idNumber as TEXT), '') as TEXT)) as "idNumber">
```

### Expected results
We would need for it to compile to
```
<md5(cast(coalesce(cast("idNumber" as TEXT), '') as TEXT)) as "idNumber">
```
otherwise the SQL won't run

### Actual results
I expect to have a way to say for the macro wether it needs to use quotation marks or not
Or alternatively work automatically like for example dbt_utils.stars works with our case sensitive tables

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/codegen
    version: 0.8.1
  - package: dbt-labs/dbt_utils
    version: 0.9.2

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.1
  - latest:    1.3.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery:  1.2.0 - Update available!
  - snowflake: 1.2.0 - Update available!
```

**Comment by joellabes** [comment]
Hey @villar1, you can resolve this using a second set of quotes: 

```
{{ dbt_utils.surrogate_key (['"idNumber"']) }} as "idNumber"
```

the single quotes will be "eaten" by Jinja to turn it into a string, but the double quotes will make it through as part of the actual command:
![image](https://user-images.githubusercontent.com/7335046/197935765-f80d686d-1f97-4b2d-8669-26e995506b8b.png)

**Comment by villar1** [comment]
Thanks for the help!
