### ISSUE TITLE
Deprecated Warnings on Recency Test

### ISSUE THREAD

**Issue by jacksond80** [dbt-labs/dbt-utils#712]
### Describe the bug

After upgrading dbt core to v1.2.0, dbt_utils.recency tests throws deprecation warnings because it uses type_timestamp, current_timestamp and dateadd macros that are now part of dbt core. 

### Steps to reproduce

Run dbt test with at least one dbt_utils.recency test configured

### Expected results

No deprecation warnings

### Actual results

Three deprecation warnings for each recency test configured.

### Screenshots and log output

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/54021375/197525222-27686a5f-9f78-4a8f-b617-650eb3f2d7c1.png">

### System information
packages:
    - package: dbt-labs/dbt_utils
      version: 0.9.2

    - git: "https://github.com/EqualExperts/dbt-unit-testing"
      revision: v0.2.3

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.3.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.2.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**Comment by joellabes** [comment]
@jacksond80 this should be resolved with utils 0.9.5, sorry about the delay!
