### ISSUE TITLE
dbt-utils 0.9.3 now requires dbt >=1.3.0-rc1?

### ISSUE THREAD

**Issue by trunyan** [dbt-labs/dbt-utils#714]
### Describe the bug
Started getting errors right after 0.9.3 was released.  Looks like you changed the required dbt versions to be` >=1.3.0-rc1`?

https://github.com/dbt-labs/dbt-utils/commit/369a2d02789bd6d96dde7c94244b85dae2251acd#diff-27386df54b2629c1191d8342d3725ed8678413cfa13b5556f59d69d33fae5425L4

### Steps to reproduce
run dbt 1.2.2
add dbt-uils 0.9.3 into packages
run `dbt deps`

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by joellabes** [comment]
Hey @trunyan, sorry about this! I have just released 0.9.4 which puts the require-dbt-version back. The package hub probably won't pick it up for another 45mins or so though.

**Comment by trunyan** [comment]
Thanks for the quick turnaround.  Cheers

**Comment by mirosval** [comment]
@joellabes Hello, it looks like `0.9.3` and `0.9.4` are not released? There is no mention of them in the Release page here on GH and also dbt Package Hub shows `0.9.2` as latest. Is this a known issue?

**Comment by joellabes** [comment]
> @joellabes Hello, it looks like `0.9.3` and `0.9.4` are not released? There is no mention of them in the Release page here on GH and also dbt Package Hub shows `0.9.2` as latest. Is this a known issue?

Hi @mirosval, sorry about this - 0.9.3 and 0.9.4 caused code intended for 1.0 to leak out and we had to delete them and roll back to 0.9.2 as the latest. I'm out of office for the next 10 days but intend to sort this out properly when I return.
