### ISSUE TITLE
Support backwards-compatibility for `surrogate_key`.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-utils#715]
### Describe the feature
As a dbt package, we would like to keep the previous functionality of `surrogate_key` for the time being, which means that we'd have to `surrogate_key_treat_nulls_as_empty_strings=true`. However, if a user who installed the package also uses `dbt_utils` on his own project, we'd override his logic as well.

As an alternative, I suggest sticking to `current_timestamp`'s solution of introducing a separate macro by implementing `surrogate_key_backcompat` which treats nulls as empty strings, rather than a `var` that changes its functionality.

**Comment by joellabes** [comment]
@elongl thank you for opening this! I agree that this is a bit trickier for package maintainers. And you've actually opened an interesting question for me around variable namespacing and precedence - I need to double check that it works correctly for packages inside a project.  

With that said, I thought a bit about this over the weekend and I am leaning towards the opinion that the behaviour should be globally consistent for a project. It feels wrong to me that two invocations of generate_surrogate_key() of the same two columns would have different results based on which model generated them.

Can you say more about why your package's models needs to retain the old behaviour under all circumstances, as opposed to following the project's configuration? 

You could coalesce any potentially-null columns to blanks inside of your models where appropriate, before passing them to generate_surrogate_key().

I haven't written the migration guide yet, but I am reasonably sure I'll encourage all existing utils users to set the backwards compatibility variable unless they're extremely confident that they don't need it. This (and the other breaking changes in utils v1) is mostly a change that makes it easier for future dbt users to succeed, but it is Bad for that change to negatively impact existing users' existing keys. 

Very interested in your thoughts on all this 🙏

**Comment by joellabes** [comment]
@elongl I'm getting very close to putting out the release candidate for v1 - if you've got any comments after ☝️ please let me know!
