### ISSUE TITLE
dbt_utils.star should indent 4 spaces to match dbt style guide

### ISSUE THREAD

**Issue by panasenco** [dbt-labs/dbt-utils#719]
### Describe the feature
Indentation behavior of the macro dbt_utils.star should match the official [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md#sql-style-guide)

### Describe alternatives you've considered
Ignore it

### Additional context
dbt_utils.star currently indents by two spaces.

### Who will this benefit?
Anyone who writes SQL code in accordance with the official dbt style guide.

### Are you interested in contributing this feature?
I can contribute it if that's OK with the maintainers. It's a one-line fix.

**Comment by joellabes** [comment]
Yep I'd merge it! Please target your PR to `utils-v1` branch though to avoid a bajillion merge conflicts 🙏
