### ISSUE TITLE
Migrated macros causing warnings in downstream packages

### ISSUE THREAD

**Issue by mirosval** [dbt-labs/dbt-utils#720]
### Describe the bug
It seems some macros have been moved to core, but there are (incorrect?) warnings generated for them from [dbt_expectations](https://github.com/calogica/dbt-expectations/issues/213).

### Steps to reproduce
1. Use dbt 1.3.0 with dbt_expectations 0.7.0 (which transitively pulls dbt-utils 0.9.2)
2. Run any dbt command that triggers parsing

### Expected results
No warnings about incorrect macros, the above dbt_expectations issue mentions they have already migrated

### Actual results
Warnings like:
```
Warning: the `type_string` macro is now provided in dbt Core. It is no longer available in dbt_utils and backwards compatibility will be removed in a future version of the package. Use `type_string` (no prefix) instead. The <model name> model triggered this warning.
```

### System information
```
---
packages:
  - package: calogica/dbt_expectations
    version: 0.7.0
  - package: tnightengale/dbt_meta_testing
    version: 0.3.6
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - redshift: 1.3.0 - Up to date!
  - postgres: 1.3.0 - Up to date!

```

### Additional context
In #714 there is a mention of a `0.9.3` and even `0.9.4` release of dbt-utils but there are no such releases available here or on dbt Hub.

We are relying on `--warn-error` flag a lot, which means that these warnings are preventing us from upgrading to dbt 1.3.0 so its a big deal for us.

### Are you interested in contributing the fix?
Looks like its a release issue so I'm not sure I can contribute, but otherwise sure!

**Comment by joellabes** [comment]
@mirosval this should be resolved with utils 0.9.5, sorry about the delay! 0.9.3 and 0.9.4 were pulled for mistakes in the release process 😬
