### ISSUE TITLE
Suggestion:  dbt_utils should use BigQuery's own PIVOT/UNPIVOT functions when running on that database

### ISSUE THREAD

**Issue by kdw2126** [dbt-labs/dbt-utils#721]
### Describe the feature
I think dbt_utils should use BigQuery's own PIVOT/UNPIVOT functions as part of its pivot/unpivot functionality when it's run in BigQuery.  

### Describe alternatives you've considered
Not really sure this is applicable for a new feature

### Additional context
Yes, database specific to BQ.  Could duplicate exact functionality of existing macro using the BQ commands so this wouldn't break anything for other database users.

### Who will this benefit?
This proposed feature has many benefits.
(1). The number of compiled lines of code to do an Unpivot goes to 8 lines instead of hundreds, avoiding the dreaded "maximum query length" error in Bigquery and making compiled code easier to read.
(2). BigQuery automatically chooses appropriate data types so we don't have to do dozens of CAST() statements.  We could keep the existing cast-to logic but automatically drop the cast statements if the user is requesting a type that BigQuery would automatically use. 
(3). This should be faster!  

### Are you interested in contributing this feature?
I would be happy to contribute this feature because I've built my own half-baked macro for this purpose in my own repo.

**Comment by joellabes** [comment]
Yes! I love swapping out our code for the native stuff 🎉 ideally the tests should continue to pass without any indication that the underlying implementation has changed; if that winds up not being possible we'll have to think a bit harder about how we do it. 

If you come across any edge cases that the tests don't cover, let me know and I'm happy to help you work out how to flesh them out further
