### ISSUE TITLE
fewer_rows_than sql error

### ISSUE THREAD

**Issue by nc-rsjo** [dbt-labs/dbt-utils#730]
### Describe the bug
There seems to be a SQL error with [fewer_rows_than](https://github.com/dbt-labs/dbt-utils/blob/0.9.5/macros/generic_tests/fewer_rows_than.sql)

### Steps to reproduce
Use fewer_rows_than on an Oracle database

### Expected results
Test Pass or Fail

### Actual results
Error 2

### Screenshots and log output
![image](https://user-images.githubusercontent.com/115219879/203805740-d54a15c0-5fe0-4e1c-bb05-47bf08bebf4d.png)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.5

**Which database are you using dbt with?**
Oracle

**The output of `dbt --version`:**
```
dbt-oracle = "^1.2.1"
```

### Additional context
SOLUTION: I suggest you remove * from the final CTE, it is not used anyway. Removing "*," fixes the problem for me

### Are you interested in contributing the fix?
This works :)

{% test fewer_rows_than(model, compare_model) %}
  {{ return(adapter.dispatch('test_fewer_rows_than', 'dbt_utils')(model, compare_model)) }}
{% endtest %}

{% macro default__test_fewer_rows_than(model, compare_model) %}

{#-- Needs to be set at parse time, before we return '' below --#}
{{ config(fail_calc = 'coalesce(row_count_delta, 0)') }}

{#-- Prevent querying of db in parsing mode. This works because this macro does not create any new refs. #}
with a as (

    select count(*) as count_a from {{ model }}

),
b as (

    select count(*) as count_b from {{ compare_model }}

),

final as (

    select
        case
            -- fail the test if we have more rows than the reference model and return the row count delta
            when count_a > count_b then (count_a - count_b)
            -- fail the test if they are the same number
            when count_a = count_b then 1
            -- pass the test if the delta is positive (i.e. return the number 0)
            else 0
        end as row_count_delta
    from a
    cross join b

)

select * from final

{% endmacro %}

**Comment by joellabes** [comment]
Hi @nc-rsjo, does Oracle not support this pattern: 
```sql
select *, id * 2 as double_id
from some_table
```
? That seems to be the case from this article: http://www.brianlim.ca/2014/02/oracle-select-and-other-fields.html 

I don't want to ditch the select * because it is helpful in debugging to have the absolute values as well as the delta, and does work for our officially-supported warehouses. 

dbt utils doesn't explicitly support Oracle natively, but I'm happy for you to make changes which add compatibility for other warehouses without breaking support for the ones we do support. 

In this case, it looks like this would be supported:
```sql
...
final as (

select
    a.count_a,
    b.count_b,
    case
        -- fail the test if we have more rows than the reference model and return the row count delta
        when count_a > count_b then (count_a - count_b)
        -- fail the test if they are the same number
        when count_a = count_b then 1
        -- pass the test if the delta is positive (i.e. return the number 0)
        else 0
    end as row_count_delta
from a
cross join b
)

select * from final
```

if you try running that and it succeeds, I'd welcome a PR 👍

**Comment by nc-rsjo** [comment]
Hi,

Yes, I can confirm that Oracle does not support the following:


select *, id * 2 as double_id



from some_table

But that following works with Oracle:


final as (







select



    a.count_a,



    b.count_b,



    case



        -- fail the test if we have more rows than the reference model and return the row count delta



        when count_a > count_b then (count_a - count_b)



        -- fail the test if they are the same number



        when count_a = count_b then 1



        -- pass the test if the delta is positive (i.e. return the number 0)



        else 0



    end as row_count_delta



from a



cross join b



)







select * from final

It would be nice if it could be corrected, but I fully understand if you prefer not to as, as you mention, Oracle is not explicitly supported natively.

All the best,

Rasmus Stenstrøm Johansen

**Comment by joellabes** [comment]
Good to know! In that case if you open a PR which makes the change, I'll happily merge it 🎉

**Comment by nc-rsjo** [comment]
I just upgraded to the latest version 1.0.0, and the addition of the "group by" to fewer_rows_than.sql induced some new PL/Sql errors. I've made a bunch of changes to my local clone of the repo, and I'm afraid I must admit that it might become too big of a compromise to make it compatible with Oracle.
I much appreciate your effort, and dbt-utils is definitely still very helpful  :)

**Comment by joellabes** [comment]
OK! I'll leave this open in case anyone else wants to take a stab at it.
