### ISSUE TITLE
`accepted_range`'s `where` option?

### ISSUE THREAD

**Issue by s-t-hg** [dbt-labs/dbt-utils#736]
### Describe the bug

According to the README, there is a where option for accepted_range, but looking at the source code, the where option does not appear to be used.

https://github.com/dbt-labs/dbt-utils/blob/84cf0f2971f5bf539b06c42373a5e80b59ba7047/README.md?plain=1#L586-L591

https://github.com/dbt-labs/dbt-utils/blob/84cf0f2971f5bf539b06c42373a5e80b59ba7047/macros/generic_tests/accepted_range.sql#L1

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: duckdb)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - duckdb: 1.3.3 - Up to date!
```

**Comment by joellabes** [comment]
Hi @s-t-hg, this is native functionality to dbt Core so the macro doesn't need to contain a `where` argument: https://docs.getdbt.com/reference/resource-configs/where 

Note that these docs refer to the more modern approach of putting `where` under a `config` block. Either works, but the new way is a bit more consistent.

**Comment by s-t-hg** [comment]
Thanks for the detailed answer!

> Note that these docs refer to the more modern approach of putting `where` under a `config` block.

I thought it did not work, but I just tried it and it seems to work.
I was confused because the notation is different from the official documentation, so if possible it would be great to have the same notation as the official documentation and a link to the official documentation in the README.

Thank you so much for your continued development of dbt.
