### ISSUE TITLE
It would helpful to have a subtraction equivalent of the `safe_add()` macro

### ISSUE THREAD

**Issue by dchess** [dbt-labs/dbt-utils#745]
Essentially this macro would function identically to [`safe_add()`](https://github.com/dbt-labs/dbt-utils#safe_add-source) but would subtract values instead. This would help eliminate the need to hack the `safe_add()` macro by multiplying values by -1 or by needing to do this without the **dbt_utils** macro using `coalesce` statements.

This function would be beneficial whenever there is a need to handle subtraction involving null values at a row level. I would be open to submitting this as PR if there is interest. I think it would require just one change to this line (but correct me if I'm wrong):
https://github.com/dbt-labs/dbt-utils/blob/42003d7f6dfeb83c8ff3169d6911cc60f5b54545/macros/sql/safe_add.sql#L26

**Comment by joellabes** [comment]
@dchess I'm into it! Feel free to open a new PR that adds a new macro 👍 (and some tests pls)

**Comment by dchess** [comment]
@joellabes I opened #748 to address this issue. Let me know if you have any feedback.

**Comment by dchess** [comment]
@joellabes Do you have a sense of which future release version this macro will be available in?
