### ISSUE TITLE
`deduplicate` drops rows that have missing (NULL) values (Redshift)

### ISSUE THREAD

**Issue by LePeti** [dbt-labs/dbt-utils#749]
### Describe the bug

As `dbt_utils.deduplicate()` uses `natural join` in Redshift, it will drop any rows from the input relation where a field is NULL.

### Steps to reproduce
1. create the following csv in dbt:

`dummy.csv`
```
userid,other_col,my_time
1,hello,1
1,bye,2
2,NULL,1
2,wow,2
```

2. upload it to your redshift db using `dbt seed -s dummy`
3. Create the following model in dbt:

`test_dedupe.sql`
```sql
{{ dbt_utils.deduplicate(
    relation=ref('dummy'),
    partition_by='userid',
    order_by='my_time asc',
)
}}
```
4. run the above model and see the result: `dbt run test_dedupe.sql`

### Expected results

```
userid, other_col, my_time
     1, hello    ,       1
     2, NULL     ,       1
```

### Actual results

```
userid, other_col, my_time
     1, hello    ,       1
```

### System information
**The contents of your `packages.yml` file:**

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6
  - package: dbt-labs/codegen
    version: 0.8.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - postgres: 1.3.0 - Up to date!
  - redshift: 1.3.0 - Up to date!
```

**The operating system you're using:** MacOS Monterey v12.6

**The output of `python --version`:** `Python 3.9.15`

### Are you interested in contributing the fix?
Yes I'd like to contribute but I've never done it before. My assumption is that instead of a `natural join` there should be an `inner join` on the single field that is provided in the `partition_by` parameter of the macro.

**Comment by joellabes** [comment]
@LePeti this is also a dupe of https://github.com/dbt-labs/dbt-utils/issues/713!
