### ISSUE TITLE
`get_filtered_columns_in_relation` returns empty string rather than empty list during parsing

### ISSUE THREAD

**Issue by joemirizio** [dbt-labs/dbt-utils#750]
### Describe the bug
The `get_filtered_columns_in_relation` macro is designed to return an array of columns. When dbt is parsing the project (`execute` is `False`), the return value is an empty string (`''`), rather than an empty list (`[]`). 

This can cause issues when the result is used in code and other macros that validates its arguments, such as the warning message in the (deprecated) `surrogate_key` macro.

It is expected that the macro returns the same data type, regardless of the execution mode.

### Steps to reproduce
1. Initialize a dbt project
2. Create `models/foo.sql`:
```sql
{% set my_columns = dbt_utils.get_filtered_columns_in_relation(from=ref('bar')) %}
{% if my_columns is not string %}
  select 'success!'
{% else %}
  {{ exceptions.warn("Invalid type of 'my_columns'")}}
{% endif %}
```
3. Create `models/bar.sql`:
```sql
select 'other' as col
```
4. `dbt run`

### Expected results
The model to be created without a warning.

### Actual results
A warning that appears during the parsing phase:
```
Invalid type of 'my_columns'
```

### System information
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: netezza)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.2
  - latest:    1.3.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - netezza: 1.1.0 - Could not determine latest version
```

### Additional context
This is where the issue is: https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/get_filtered_columns_in_relation.sql#L11

### Are you interested in contributing the fix?
Sure!

**Comment by joellabes** [comment]
Hey @joemirizio, I _think_ this is a safe change to make! Give it a whirl and let's see how the CI goes - but if we release it and it turns out that it interferes with some existing behaviour somewhere we might have to revert in a speedy patch release. 

I assume that 
> the warning message in the (deprecated) surrogate_key macro.

is not the only place you're seeing difficulty? I'm not that concerned about a deprecated macro having a bad time... everyone's meant to stop using it anyway!
