### ISSUE TITLE
date_spine doesn't work when start_date and end_date are the same

### ISSUE THREAD

**Issue by ian-whitestone** [dbt-labs/dbt-utils#751]
### Describe the bug

Using `dbt_utils` v1.0.0

date_spine fails when `start_date` and `end_date` are the same.

```sql
    {{ dbt_utils.date_spine(
            datepart="day",
            start_date="'2023-01-05'",
            end_date="'2023-01-05'"
        )
    }}
```

produces:

```
23:25:03  Finished running 1 table model in 0 hours 0 minutes and 3.46 seconds (3.46s).
23:25:03  
23:25:03  Completed with 1 error and 0 warnings:
23:25:03  
23:25:03  Compilation Error in model daily_spend (models/daily_spend.sql)
23:25:03    upper bound must be positive
23:25:03    
23:25:03    > in macro default__get_powers_of_two (macros/sql/generate_series.sql)
23:25:03    > called by macro get_powers_of_two (macros/sql/generate_series.sql)
23:25:03    > called by macro default__generate_series (macros/sql/generate_series.sql)
23:25:03    > called by macro generate_series (macros/sql/generate_series.sql)
23:25:03    > called by macro default__date_spine (macros/sql/date_spine.sql)
23:25:03    > called by macro date_spine (macros/sql/date_spine.sql)
23:25:03    > called by model daily_spend (models/daily_spend.sql)
23:25:03    > called by model daily_spend (models/daily_spend.sql)
```

If you run:

```sql
    {{ dbt_utils.date_spine(
            datepart="day",
            start_date="'2023-01-05'",
            end_date="'2023-01-06'"
        )
    }}
```

It works fine

### Expected results

Generate a table/CTE with a single date

### System information
**The contents of your `packages.yml` file:**

```sql
packages:
  - git: https://github.com/get-select/dbt-snowflake-monitoring.git
    revision: 1.3.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.3.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!
```

**Comment by joellabes** [comment]
Hey @ian-whitestone, thanks for opening this! You've found a fun edge case. 

Since there is a straightforward workaround and (IMO) there's nothing in the argument names that promises a `>` and `<=` pairing vs `>` and `<`, I'm inclined to close this as wontfix, _especially_ since it would be a breaking change for people who already have it set up. 

With dbt utils v1 out, we're committed to no breaking API changes until the next major version which I'm intending to not be until dbt Core v2 if I can manage. 

Let me know if you strongly disagree!
