### ISSUE TITLE
dbt_utils.star except parameter only recognizes hardcoded values and not variables

### ISSUE THREAD

**Issue by Alex-Ciorra** [dbt-labs/dbt-utils#761]
### Describe the bug

dbt_utils.star "except=" parameter only recognizes hardcoded values and not variables as expected. 

### Steps to reproduce

Trying to create a macro that selects all the fields from a landing table except for the "INGESTION_TIMESTAMP". The 'call_macro_test' initializes the variables, however the issue still arises even when setting the variables within the 'test_copy_into' macro.

```
{% macro test_copy_into(table_relation, excluded_column) -%}

{% set table_relation = ref('stg_sp_ins_company_reporting_config') %}
{% set excluded_column = 'INGESTION_TIMESTAMP' %}


{% set SQL %}

SELECT 
{{ dbt_utils.star(from=table_relation, except=["{{excluded_column}}"]) }}
FROM {{table_relation}}
{% endset %}

{% do log( 'test:' ~ SQL , info=True) %}
{% do log('excluded_column(s): ' ~ excluded_column, info=true) %}



{%- endmacro -%}
```
Passing variables as macro arguments within a seperate macro:
```
{% macro test_copy_into(table_relation, excluded_column) -%}

{% set SQL %}

SELECT 
{{ dbt_utils.star(from=table_relation, except=["{{excluded_column}}"]) }}
FROM {{table_relation}}
{% endset %}

{% do log( 'test:' ~ SQL , info=True) %}
{% do log('excluded_column(s): ' ~ excluded_column, info=true) %}


{%- endmacro -%}

-- BELOW WILL BE PART OF NS_COPY_INTO
{% macro call_macro_test() %}

{{ test_copy_into(
    table_relation = ref('stg_sp_ins_company_reporting_config')
    , excluded_column = 'INGESTION_TIMESTAMP'
) }}

{%- endmacro -%}
```

### Expected results

expected output in the log would be:
```
SELECT 
"ID",
  "PARENTINSCOMPANYNAME",
  "PARENTINSCOMPANYGROUPING",
  "DRPPROGRAMFLAG",
  "TOP20CARRIERFLAG",
  "CREATEDONUTC",
  "LASTUPDATEDONUTC",
FROM DB_PROD.STANDARD.stg_sp_ins_company_reporting_config
21:12:58  excluded_column(s): INGESTION_TIMESTAMP
```

### Screenshots and log output

![image](https://user-images.githubusercontent.com/118456415/213296689-68ad9ed6-9127-4be0-9e26-823e12a3f7bb.png)

### System information
**The contents of your `packages.yml` file:**
![image](https://user-images.githubusercontent.com/118456415/213297077-4359f1af-b308-463c-955d-550780bbf074.png)

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
version: '1.0.0'
```

### Additional context

I'm able to see that the log ouput is accepting the excluded_column value of 'INGESTION_TIMESTAMP' but is unrecognized in the dbt_utils.star macro. I believe the issue is within the dbt_utils.star except parameter.

**Comment by joellabes** [comment]
Hey @Alex-Ciorra, you don't need the second set of curly brackets around `excluded_column` in the except block: https://docs.getdbt.com/docs/building-a-dbt-project/dont-nest-your-curlies 

try this: 

```
{% macro test_copy_into(table_relation, excluded_column) -%}

{% set table_relation = ref('stg_sp_ins_company_reporting_config') %}
{% set excluded_column = 'INGESTION_TIMESTAMP' %}


{% set SQL %}

SELECT 
{{ dbt_utils.star(from=table_relation, except=[excluded_column]) }}
FROM {{table_relation}}
{% endset %}

{% do log( 'test:' ~ SQL , info=True) %}
{% do log('excluded_column(s): ' ~ excluded_column, info=true) %}



{%- endmacro -%}
```
