### ISSUE TITLE
Formatting bug with TOC links

### ISSUE THREAD

**Issue by bbrewington** [dbt-labs/dbt-utils#770]
here's an example LOC in the README: https://github.com/dbt-labs/dbt-utils/blob/dcc9f47e805dbe83e862628591d2451c29cee7b5/README.md?plain=1#L13

Expected:
* [equal_rowcount (<a href="macros/generic_tests/equal_rowcount.sql">source)</a>](#equal_rowcount-source)

Actual:
* [equal_rowcount (<a href="macros/generic_tests/equal_rowcount.sql">source</a>)](#equal_rowcount-source)

Potential Cause:
* auto-formatting of TOC from this PR: https://github.com/dbt-labs/dbt-utils/pull/486

**Comment by joellabes** [comment]
Hey @bbrewington, good eagle eyes! 

What is your ideal solution here? If anything, this feels like an issue to open against https://github.com/ekalinin/github-markdown-toc, as IMO the benefit of the TOC staying up to date outweighs the downside of a funky looking parenthesis, so I wouldn't be keen to revert 486.

**Comment by bbrewington** [comment]
Oh interesting - yeah, agreed w/ added benefit outweighs need to revert

I’ll take a look at that rep
