### ISSUE TITLE
"Fill Value" argument request for union_relations

### ISSUE THREAD

**Issue by Horizon-cmchugh** [dbt-labs/dbt-utils#772]
Hi there,

I was using the `union_relations` macro to combine two datasets. Works great, but one thing I wish there was an option to do would be to have an argument to choose what to fill the `null` values for non-matching columns with.

For example, the datasets I was combining both contain the same dimension columns (time / location), but don't contain the same numeric metric fields. It would be useful for me to have the non-matching criteria be entered as as `0` instead of a `null` value as I use this data for modeling and have been using `nvl` to coerce the data to 0 before summing.

I was considering if a `fill_value` argument could be added to fill the unmatched columns with a whatever the argument is set to? I think this would add more flexibility to the `union_relations` macro than it currently allows and would generally make the function even more useful.

Appreciate it!

**Comment by joellabes** [comment]
Hey @Horizon-cmchugh, this feels reasonable as long as it defaults to `null` for backwards compatibility reasons! I'd welcome a PR that changed this (and added tests)
