### ISSUE TITLE
Variable override for legacy/new behavior in generate_surrogate_key()

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-utils#777]
### Describe the feature
In 1.0.0, the new `generate_surrogate_key()` macro was added, with a project-level variable to control whether the new (distinguish nulls from empty strings) behaviour is used or not.

Because variables can't be namespaced, we cannot override the default behaviour for specific uses of the macro.  My proposal is to add an additional, optional (for backwards compatibility) argument to the macro which overrides any variable-driven behaviour, eg:

```jinja
{% macro generate_surrogate_key(field_list, treat_nulls_as_empty_strings=None) %}
```

1. If the variable isn't provided, the macro works as it currently does.
2. If the variable is provided, the value of the variable overrides whatever the default or var-driven behaviour for the project is.

### Describe alternatives you've considered

Duplicating the logic for the macro for the non-default case.  I don't like this as much as any other bugfixes to the macro wouldn't be propagated to my dupe.

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
PR incoming.

**Comment by joellabes** [comment]
nice issue number ;) 

Thank you for opening and for your patience while I was away! I am not _very_ excited about this, but I am willing to be sold on it if you've got a compelling use case. 

The reason there isn't any configurability beyond the project-wide definition is that in my opinion, surrogate keys should be globally consistent. 

_(As I type this, I develop cold sweats about the implications of our forthcoming multi-project world 😬 brb gotta write something in Slack)_

OK back to it: right now, you can trust that any surrogate key you encounter in your project can be safely joined with its peers. Likewise, by having a single global variable, you can be reasonably confident that the components of a single key won't get arbitrarily changed by someone - they would have to change it everywhere, which adds enough friction to make them rethink their choices. 

In other words, I consider the fact that this is hard and annoying to be a feature. But I definitely could be wrong! 

If you didn't want to duplicate the macro, some other options: 

## Still call the official macro, but only after cleaning up the inputs
```sql
--macros/generate_surrogate_key_joshs_version.sql

-- this is not actually production-ready code, but you get the picture

{% macro generate_surrogate_key_joshs_version(fields, treat_nulls_as_empty_strings=None) %}
  {% set cooler_fields = [] %}
  {% for field in fields %}
    {% if treat_nulls_as_empty_strings %}
      {% do cooler_fields.append('coalesce(' ~ field ~ ', "")') %}
    {% else %}
      {% do cooler_fields.append(field) %}
    {% endif %}
  {% endfor %}
  {% do return (dbt_utils.generate_surrogate_key(cooler_fields) %}
{% endmacro %}
```

```sql
--models/my_model.sql
select 
  a, 
  b, 
  {{ generate_surrogate_key_joshs_version(['c', 'd', 'e'], True) }} as surr_key
from {{ ref('my_model') }}
```

Which would retain all the existing macro behaviour and subscribe you to future fixes, but also guarantee that anything going in has been converted to a blank string. 

## Do one-off fixes in the model itself:

```sql
--models/my_model.sql
select 
  a, 
  b, 
  {{ dbt_utils.generate_surrogate_key(["coalesce(c, '')", "d", "e"]) }} as surr_key
from {{ ref('my_model') }}
```

## Convince me I'm being overly paranoid 
```
No sample code available, but I believe in you! 
```

**Comment by jaypeedevlin** [comment]
> right now, you can trust that any surrogate key you encounter in your project can be safely joined with its peers.

Yeah, I see, that is a <danger>. I managed to miss that becaused, despite using SK's for joining all over the place in the past, a lot of the time I'm not using them for joining these days and instead to provide a column for incrementals to merge on (for fact-like tables where joining to other facts isn't really done).

I think given your point I'm likely to lean towards _Still call the official macro, but only after cleaning up the inputs_, which is a variation of 'reimplement the logic by a different name' that I already did to get the thing done before creating this issue/PR.
