### ISSUE TITLE
Add ability to run union_relations for dbt test, not ony dbt run or compile

### ISSUE THREAD

**Issue by lokofoko** [dbt-labs/dbt-utils#781]
### Describe the feature

I want to be able to use the `union_relations` macro in my test with `dbt test`
This line prevent from execution in tests as being said here https://docs.getdbt.com/reference/dbt-jinja-functions/execute
<img width="170" alt="image" src="https://user-images.githubusercontent.com/54797607/233052590-2f65e91d-2cc0-4e53-ae43-8562df96dd00.png">

### Describe alternatives you've considered

Manual writing union all for all relations

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

Shouldn't be

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

Everyone who will possibly write tests and want to use union_relations macro.

**Comment by joellabes** [comment]
>This line prevent from execution in tests as being said here https://docs.getdbt.com/reference/dbt-jinja-functions/execute

Can you clarify what you mean here? I made a quick singular test:

```
with inputs as (

    {{ dbt_utils.union_relations(
    relations=[ref('my_first_dbt_model'), ref('my_second_dbt_model')]) }}
)

select * from inputs
```

and ran `dbt test`, and it correctly unioned the two models

**Comment by lokofoko** [comment]
Yeah, you're right, my bad. I might miss something. Thanks for the fast response.
