### ISSUE TITLE
dbt_utils.union_relations() does not work with GEOGRAPHY data type 

### ISSUE THREAD

**Issue by muhammad-fasih58** [dbt-labs/dbt-utils#793]
### Describe the bug

[dbt_utils.union_relations()](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/union.sql) uses a CAST function to standardize the columns however, Snowflake does not support CAST operation to GEOGRAPHY datatype. [read more here](https://docs.snowflake.com/en/sql-reference/functions/try_cast#usage-notes)

### Steps to reproduce

A simple dbt model with GEOGRAPHY column can be UNION-ed with any other model using this macro and it will throw out the error

Here's a Snowflake SQL snippet:
```
select cast(null as GEOGRAPHY) as "LOCATION"; --error!
select try_cast(null as GEOGRAPHY) as "LOCATION"; --error!

-- invalid type [CAST(null AS GEOGRAPHY)] for parameter 'TO_GEOGRAPHY'
````

### Expected results

This macro to cater for GEOGRAPHY datatype in Snowflake and not throw an error. 

### Screenshots and log output

![image](https://github.com/dbt-labs/dbt-utils/assets/8229608/a0f6254e-13a3-400e-a9f1-a371a0fc5a49)

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0

  - package: dbt-labs/audit_helper
    version: 0.8.0

```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.5
  - latest:    1.5.0 - Update available!
```

### Additional context

[Link to code](https://github.com/dbt-labs/dbt-utils/blob/965726ea4a1cf2d793ec93ade5d39a884c8dc577/macros/sql/union.sql#L111)

**Comment by joellabes** [comment]
Hey @muhammad-fasih58, do you have any extra context around what _does_ work? What is the expected way to create a null column of `geography` type?

**Comment by paperlinguist** [comment]
Adding additional tests for snowflake:
![image](https://github.com/dbt-labs/dbt-utils/assets/56840370/ee43577b-2b00-4b44-afab-3de29b5009de)

The best solution I can think of is to just insert a null as that is supported rather than trying to cast it to a geo field.
