### ISSUE TITLE
get_single_value sql macro: default value condition can not be satisfied

### ISSUE THREAD

**Issue by marrigault** [dbt-labs/dbt-utils#804]
### Describe the bug
Default value is not used when sql statement of get_single_value macro do not return any result

### Steps to reproduce
Sql statement on empty table or whatever query that do not return any result

### Expected results
get_single_value macro should return default parameter when query is not returning a single value

### Actual results
get_single_value macro return None as a result

### System information
**The contents of your `packages.yml` file:**
  - package: dbt-labs/dbt_utils
    version: 1.0.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.5.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.3.0 - Update available!
```

### Additional context
I think line 18: {% if r | length == 0 %}
could be replaced with 
{% if not r[0] %} (or maybe {% if not (r and r[0]) %}  )
because r has a value even if query has no result

**Comment by tsafacjo** [comment]
can I take it ?

**Comment by marrigault** [comment]
Sure 👍
