### ISSUE TITLE
add error for union macro when table does not exist

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-utils#81]
This trips people up all the time, typically when a model is made `ephemeral`. The macro should throw an error when no columns are found for the specified relation.

**Comment by clrcrl** [comment]
As additional context:
I tried to work around this at one point by creating a version of the macro that uses
`get_columns_in_query` to get the column names

        {% if not cols and execute %}
            {{ log(get_columns_in_query("select * from " ~ (relation)), info=True) }}
        {% endif %}
The problem was that the ephemeral CTE didn't get injected so the query failed 🤷‍♀️
