### ISSUE TITLE
`_is_relation` macro fails for relations from `adapter.get_relation` on Bigquery.

### ISSUE THREAD

**Issue by PBalsdon** [dbt-labs/dbt-utils#817]
### Describe the bug
If we define a relation from the `adapter.get_relation` macro, it causes a compiler error in the `{{ dbt_utils._is_relation() }}` macro. This is in Bigquery. I've tried it in various versions of dbt-utils and dbt

### Steps to reproduce

Make a file with the following code
```jinja
{% set relation=adapter.get_relation(
      database=target.database,
      schema=target.schema,
      identifier="stg_dates" ## REPLACE WITH AN EXISTING MODEL ##
) -%}

{{relation is mapping}} -- Returns True
{{ dbt_utils._is_relation(relation, 'test_call') }}
```

Compile this file.

### Expected results
No errors, the file compiles with `True -- Returns True`

### Actual results
Compiler error
<img width="498" alt="image" src="https://github.com/dbt-labs/dbt-utils/assets/93205864/a67762b3-62d0-4ae2-bba8-3582aae62c8f">
### System information
**The contents of your `packages.yml` file:**
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
dbt cloud:
<img width="498" alt="image" src="https://github.com/dbt-labs/dbt-utils/assets/93205864/fb1c0108-90b9-4606-a00e-9ed9bac393f1">

### Additional context
I originally discovered this as a bug in `audit_helper`, but isolated the issue to this macro in dbt_utils.

### Are you interested in contributing the fix?
In theory, yes - in reality I have no idea what's going on here and it's baffling me.

**Comment by vinit2107** [comment]
Hi @PBalsdon ,
You want DBT to execute the `dbt_utils._is_relation` only when you run the code. You can control it by wrapping the code around `{% if execute %}` block, something like this.
`
{% set relation=adapter.get_relation(
      database=target.database,
      schema=target.schema,
      identifier="stg_dates" ## REPLACE WITH AN EXISTING MODEL ##
) -%}

{{relation is mapping}} -- Returns True
{% if execute %}
{{ dbt_utils._is_relation(relation, 'test_call') }}
{% endif %}
`
If my understanding is correct, you will have `relation` only after you execute your script. More documentation [here](https://docs.getdbt.com/reference/dbt-jinja-functions/execute).
Let me know if it solves your issue.

**Comment by PBalsdon** [comment]
Thank you, I believe you are correct that we need the if execute. this solved my issue
