### ISSUE TITLE
`generate_surrogate_key` fails on SQL Server with one field

### ISSUE THREAD

**Issue by jlkravitz** [dbt-labs/dbt-utils#827]
The culprit line is here: https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/sql/generate_surrogate_key.sql#L27C35-L27C35

```sql
select a, b, c, d, {{ dbt_utils.generate_surrogate_key(["a"]) }}
from my_table
```

results in error 

```bash 
('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The concat function requires 2 to 254 arguments. (189) (SQLMoreResults)')```

I would expect this not to error.

**Comment by vinit2107** [comment]
Hi @jlkravitz ,
The issue is because of this [code](https://github.com/dbt-msft/dbt-sqlserver/blob/master/dbt/include/sqlserver/macros/utils/concat.sql).

```
{% macro sqlserver__concat(fields) -%}
    concat({{ fields|join(', ') }})
{%- endmacro %}
```
You will need to add length validations here and remove concat if the `length = 1`. Happy to contribute if you want me to work on it, or you can take it forward 🙂.

**Comment by jlkravitz** [comment]
Oh great! I'm happy to take a stab at it.

@vinit2107 Just out of curiosity as I learn this codebase, where can I find the code that dispatches [this](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/sql/generate_surrogate_key.sql#L27) call to `concat` to its SQL-backend specific implementation (e.g., SQL Server)?

**Comment by vinit2107** [comment]
Hi @jlkravitz ,
Sorry for the delay. You can find the concat macro in dbt-core [here](https://github.com/dbt-labs/dbt-core/blob/3f5ebe81b9039b33a57b9aa8b1f5cb1edcd8790f/core/dbt/include/global_project/macros/utils/concat.sql#L2).

**Comment by bleiho-oc** [comment]
Hi all, same error for the Micosoft Fabric Adapter.
