### ISSUE TITLE
Add `if execute` check within `_is_relation`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-utils#833]
Context: https://github.com/dbt-labs/dbt-core/issues/7024#issuecomment-1711400453

### Describe the feature

More consistent behavior in `_is_relation` at parse time, to avoid raising confusing errors.

It's quite common to call `get_relation` or `load_cached_relation`, and then pass it into a macro that validates the input via `_is_relation`. That validation can't happen at parse time — because dbt **hasn't yet connected to the database** and doesn't yet have access to the adapter/relation cache, those methods return `None` instead of a `Relation` object.

I'd propose updating the logic of [`_is_relation`](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/jinja_helpers/_is_relation.sql#L1-L5) to check `if execute` before raising an exception. Something like:

```
{% macro _is_relation(obj, macro) %}
    {%- if execute and not (obj is mapping and obj.get('metadata', {}).get('type', '').endswith('Relation')) -%}
        {%- do exceptions.raise_compiler_error("Macro " ~ macro ~ " expected a Relation but received the value: " ~ obj) -%}
    {%- endif -%}
{% endmacro %}
```

We should probably do the same for [`_is_ephemeral`](https://github.com/dbt-labs/dbt-utils/blob/main/macros/jinja_helpers/_is_ephemeral.sql), since `ref`s don't _actually_ resolve at parse time either. (They will return a `Relation` object, but it's a pointer to _this_ model, not the actually referenced model.)

### Describe alternatives you've considered

- Adding these `if execute` no-op checks within the macros that require introspection, sequentially _before_ the call to `_is_relation`. This is already the case for some macros (e.g. [`equality`](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/generic_tests/equality.sql#L17-L23)), but not others (e.g. [`get_filtered_columns_in_relation`](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/sql/get_filtered_columns_in_relation.sql#L6-L12).
- Actually moving this macro into `dbt-core`: https://github.com/dbt-labs/dbt-core/issues/5316

### Who will this benefit?

Anyone using introspective `dbt_utils` macros who don't yet understand the finer nuances of [the adapter cache](https://www.notion.so/dbtlabs/The-Adapter-Cache-8de07620c80049c4ae66cf576fff3ac5) + [parsing vs. compilation vs. runtime](https://www.notion.so/dbtlabs/Parsing-vs-Compilation-vs-Runtime-a368808c5e164df7b481431490a2ba01) (internal docs)

### Are you interested in contributing this feature?

sure!

**Comment by vinit2107** [comment]
Linking #817 
I think it's the same issue.

**Comment by danielefrigo** [comment]
this is causing issues also to me
