### ISSUE TITLE
Add a test is_constant

### ISSUE THREAD

**Issue by remilepriol** [dbt-labs/dbt-utils#835]
### Describe the feature
I want a test checking whether a certain field is constant across a certain group by. This is simply the opposite of the `not_constant` test. 

### Describe alternatives you've considered
I have implemented it myself, but I see it as generic enough to be featured in dbt-utils.

### Who will this benefit?
I guess it could be useful to most dbt users. For instance I used it to check that a timezone is constant across several territories. I am raising this issue to see if anyone else is interested.

### Are you interested in contributing this feature?
Yes. Here is a working implementation, which is a trivial modification of the test `not_constant`. Note that it should be made generic again.

```sql
{% test is_constant(model, column_name, group_by_columns = []) %}

{% if group_by_columns|length() > 0 %}
{% set select_gb_cols = group_by_columns|join(' , ') %}
{% set groupby_gb_cols = 'group by ' + group_by_columns|join(',') %}
{% endif %}


select {{ select_gb_cols }}, count(distinct {{ column_name }}) as distinct_count

from {{ model }} {{ groupby_gb_cols }}

/* if count distinct column is greater than 1, it means the value is not constant
so we should return it to raise an error. */
having count(distinct {{ column_name }}) > 1

{% endtest %}
```

**Comment by james-johnston-thumbtack** [comment]
If it would be accepted by this project, I would be happy to submit a PR for review.
