### ISSUE TITLE
get_table_by_prefix doesn't work on Bigquery

### ISSUE THREAD

**Issue by LeTristanB** [dbt-labs/dbt-utils#88]
https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/get_tables_by_prefix.sql#L6

Bigquery doesn't support the || operators. In Bigquery Standard SQL concatenation is done with `CONCAT()`. The current macro generate an error : `400 Syntax error: Unexpected "|" at [4:36]`

Bigquery doesn't support the `ilike` function. The current macro generate an error : `Unexpected identifier "ilike"`

The macro queries the `information_schema.tables` which does'nt exist in Bigquery. To list tables in a dataset the table is `<dataset_name>.__TABLES__`

**Comment by LeTristanB** [comment]
I got this macro working for bigquery:

```
{% macro get_tables_by_prefix(schema, prefix, exclude='') %}

    {%- call statement('tables', fetch_result=True) %}

        select distinct
            concat(dataset_id, '.', table_id) as ref
        from {{ schema }}.__TABLES__
        where lower(table_id) like lower('{{ prefix }}%')
        and lower(table_id) not like lower('{{ exclude }}')

    {%- endcall -%}

    {%- set table_list = load_result('tables') -%}

    {%- if table_list and table_list['data'] -%}
        {%- set tables = table_list['data'] | map(attribute=0) | list %}
        {{ return(tables) }}
    {%- else -%}
        {{ return([]) }}
    {%- endif -%}

{% endmacro %}
```

**Comment by drewbanin** [comment]
thanks for the report @LeTristanB! dbt has a mechanism, the `adapter macro`, which makes it possible to override macros for different adapters. I think this is one case where it might make sense to just define different SQL for bigquery, then call the adapter macro in the body of `get_tables_by_prefix`.

You can see an example of an adapter macro [here](https://github.com/fishtown-analytics/dbt/blob/3dc2c9126dee81ecc766509ebead7a1c23224040/dbt/include/global_project/macros/adapters/bigquery.sql#L43-L47) and [here](https://github.com/fishtown-analytics/dbt/blob/3dc2c9126dee81ecc766509ebead7a1c23224040/dbt/include/global_project/macros/adapters/common.sql#L48-L50)
