### ISSUE TITLE
try_cast only works for strings

### ISSUE THREAD

**Issue by jwerderits** [dbt-labs/dbt-utils#89]
[dbt_utils.safe_cast](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/cross_db_utils/safe_cast.sql) does not work for snowflake.

`try_cast` only works for string expressions. 

Got error `dict object` has not attribute `string_literal` when using `dbt_utils.union_tables`

Solution was to change https://github.com/fishtown-analytics/dbt-utils/blob/d2139c265f4adfb2cb9647bf933bc95c4a3e0fff/macros/sql/union.sql#L67 
to `{{ col_name }}::{{ col_type }} as {{ col.quoted }} {% if not loop.last %},{% endif %}`

**Comment by jtcohen6** [comment]
Reference: https://docs.snowflake.net/manuals/sql-reference/functions/try_cast.html

**Comment by dapearce** [comment]
I just upgraded dbt utils and am hitting this same issue with `dbt_utils.union_table`. The error starts in our project at version 0.16
