### ISSUE TITLE
Remove file of old dbt logo

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-utils#890]
### Describe the documentation update

[This](https://github.com/dbt-labs/dbt-utils/blob/a40be2be19616c59fbab90f4fb5c98eacad23a77/etc/dbt-logo.png) file contains the old dbt logo.

If it's unused, then we can just remove it. If it is used, then we should update it with the current logo.

**Comment by anks2024** [comment]
On searching the entire dbt_labs organization, I see that the `dbt-logo.png` is not being used anywhere
<img width="1011" alt="Screenshot 2024-07-09 at 9 09 48 PM" src="https://github.com/dbt-labs/dbt-utils/assets/6273915/e059eb5f-494c-4c34-b4f2-0b8c0de7e4ce">
<img width="967" alt="Screenshot 2024-07-09 at 9 09 34 PM" src="https://github.com/dbt-labs/dbt-utils/assets/6273915/4ee9e907-1414-4219-9f9d-46cc1181a19b">

I believe it is safe to delete.
