### ISSUE TITLE
Mutually exclusive ranges support same start and end dates

### ISSUE THREAD

**Issue by michelbadetti** [dbt-labs/dbt-utils#927]
### Describe the bug
Using DBT on BigQuery, mutually exclusive ranges test, the highlited line throws a test error. Although, using date ranges (rather than timestamp ranges) and considering that most DBMS have an inclusive "between" operator for dates, it is a legitimate practice to close a date period on D-day when the next period starts at D+1.
![image](https://github.com/dbt-labs/dbt-utils/assets/34511780/1678a5b0-359a-49d8-8364-f62586898cfb)

### Steps to reproduce
Using DBT on BigQuery, this configuration block in Yaml file should cover the issue reproduction 

![image](https://github.com/dbt-labs/dbt-utils/assets/34511780/3ae7f5e6-bc6f-4185-9622-f4ee513e193d)

### Expected results
On DBMS inclusive "between" operator for dates, when using date ranges, rather than timestamp ranges, having start date = end date should be allowed. Either using a specific option or by default.

### Actual results
Par of the result as of now can be seen in the following picture, where start date = end date. 
![image](https://github.com/dbt-labs/dbt-utils/assets/34511780/bcb79f8d-6cdf-409c-8b9b-ea465e5c0ebc)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: elementary-data/elementary
    version: 0.15.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.13

Plugins:
  - bigquery: 1.7.7
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @michelbadetti !

Did you try `zero_length_range_allowed=True`?

Here's one of the examples from the [docs](https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#mutually_exclusive_ranges-source):

<img width="473" alt="image" src="https://github.com/user-attachments/assets/beda8765-7e94-441e-8dc9-3b3a87068684">

**Comment by michelbadetti** [comment]
Hello @dbeatty10, 

My bad then, I thought i had thouroughly read the documentation !

Thank you for your feedback, it solved my issue as could be expected.

**Comment by dbeatty10** [comment]
No worries @michelbadetti, so glad you were able to accomplish your goal 🎉
